### ISSUE TITLE
Memory Usage for XML output is very high

### ISSUE THREAD

**Issue by whart222** [gcovr/gcovr#1]
For my project (Gromacs) the memory usage of gcovr is extremely high when using the XML output (-x). It tops at about 1GB. This is with the version from https://software.sandia.gov/trac/fast/export/2745/gcovr/trunk/scripts/gcovr 

(from ticket 3922)

**Comment by TiloW** [comment]
I'm facing a similar issue with gcovr 3.2 using too much memory for XML output.
This is especially problematic for me because it increases build time due to swapping.

I've compared the three generators on my local machine (which has sufficient memory).

|         | *.gcov | *.gcno |
|---------|--------|--------|
| Number of Files    | 388 | 612 |
| Size of Files [MB] |  14 | 141 |

|         | Plain Text | HTML | XML |
|---------|------------|------|-----|
| Peak Memory [KB] | 94280 | 97076 | 2505896 |
| Runtime         | 2.70  | 2.01 | 3.74 |

As you can see, runtime is generally not a problem but memory usage is.
XML output uses 25 times the memory of any other generator.

Is there a special reason for using `MiniDom` instead of `ElementTree` or `lxml`?
