### ISSUE TITLE
GCNO files without GCDA pair is not displayed in html

### ISSUE THREAD

**Issue by mrx23dot** [gcovr/gcovr#100]
Some times MinGW doesn't generate GCDA file for uncovered GCNO file.
And those files are not displayed in html, so we might forget to write test cases for them.
A placeholder (uncovered html) would be nice for these source files.

**Comment by marco-c** [comment]
The solution would be to make gcovr run gcov for each GCNO file and not for each GCDA file.
This would generate a report for uncovered source files too (showing them as uncovered).

**Comment by latk** [comment]
Gcovr does run for .gcno files even when no .gcda was found so this use case should already work.

Nevertheless, there have been repeated issues with this. Possibly, this depends on the exact gcov version being used, as there are reports of gcov *refusing* to produce a gcov file without coverage (like #298, which also mentions #33 and #154).

Until a reproducible example is made available by affected users, this cannot  be fixed. I am closing in the meanwhile.

**Comment by latk** [comment]
This seems to have been an upstream bug in some versions of gcov. Users can avoid this by **upgrading GCC**. I think this bug was fixed in GCC Revision 239413 on 2016-08-12 (gcc-mirror/gcc@6d5f72f3176e6a0da33bb3495f0f4797cc2ad9db). I would expect all later [releases](https://gcc.gnu.org/releases.html) (5.5+, 6.2+, 7+) to include the fix.
