### ISSUE TITLE
Possiblity to give output folder for html

### ISSUE THREAD

**Issue by mrx23dot** [gcovr/gcovr#101]
Please provide a parameter where we can give where GCOVR should put the generated html files.
Right now it just places them next to the gcnos. HTML files should remain portable (not depend on anything else, and use relative paths)

eg. --out_folder="C:\reports\proj1\coverage_data"

**Comment by joto** [comment]
Using the `-o` parameter with a subdirectory works fine: `gcovr -o DIR/index.html` for instance. The directory must exist.

**Comment by mrx23dot** [comment]
Only the index.html gets placed there, not the other modules' htmls in html details. It could also create the dir if it doesn't exist.

**Comment by joto** [comment]
On my system (gcovr 3.2) it puts all files in that directory. And yes, I agree, it should create that directory.

**Comment by r-barnes** [comment]
Creating the directory if it doesn't exist would be handy.

**Comment by latk** [comment]
@r-barnes I've thought about that issue a lot, but think that _not_ creating the directory is how `-o` options typically work. More precisely, only the last segment of the path given to `-o` should be created or overwritten.

However, it might be reasonable to change this option so that it accepts paths with a trailing slash to indicate a directory that should be created, and then auto-select a filename in the directory (probably `index.html`). What do you think? Maybe we can spec this out in a separate issue.
