### ISSUE TITLE
License Handling for script

### ISSUE THREAD

**Issue by kreuzberger** [gcovr/gcovr#111]
Hi!
i used the gcovr script to visualize my cmake script coverage. Therefore i adapted the parsing of the files to fill the CoverageData Structure, and use the xml / html output to display cmake script coverage.

Questions is how to handle the license if i would release the script on github cause it is derived from the "original" gcovr code

- Do i have to use the License.txt from gcovr?
- Do i have to use the copyright in the script base?

OR
- can i put it on any other free license

**Comment by whart222** [comment]
It generally suffices to provide a reference in the source to the original source, and a reference to the original license.  Sometimes I see a copy of the original license included.

Since gcovr uses the BSD 3-Clause license, you can pick virtually any open source license for you code and it will be compatible.
