### ISSUE TITLE
gvocr vs lcov

### ISSUE THREAD

**Issue by anderspitman** [gcovr/gcovr#132]
Could someone give a quick rundown of gcovr vs lcov? From what I can see, the XML output seems to be the largest distinguishing feature of gcovr. The HTML output (which is probably more relevant for me)  seems to be heavily inspired by lcov. I guess the two projects seem so similar that I'm wondering what the rationale for creating gcovr was? I'm trying to figure out which would be best for my needs.

**Comment by jsiirola** [comment]
lcov is a far older project.  gcovr was originally created as a simple script to provide a convenient command line interface to gcov that produced more easily digestible output similar to python's coverage utilities.  We later added XML output for integration with the Jenkins continuous integration server's Cobertura plugin so that we could get nice coverage reporting of C/C++ codes in Jenkins.  HTML output was added much later.  If all you need is HTML, pick whichever one produces the output you like better or integrates easier with your existing workflow.

**Comment by anderspitman** [comment]
Perfect, thanks.

**Comment by bryceschober** [comment]
Might be nice to add that info to the README, since it answered my question.

**Comment by latk** [comment]
@bryceschober That's a good idea! I created a [FAQ on the gcovr website](https://gcovr.com/faq.html) with this item. Please let me know if you see any other candidates for inclusion in the FAQ.
