### ISSUE TITLE
Add support to the latest Cobertura format

### ISSUE THREAD

**Issue by lmussier** [gcovr/gcovr#164]
Hi,

Could you add the support of the latest cobertura format [coverage-04.dtd](https://github.com/cobertura/web/blob/master/htdocs/xml/coverage-04.dtd)  for xml output?

Thanks.

**Comment by dishmal** [comment]
Any idea of if/when this would happen to support TFS usage?

**Comment by shreyaskambl** [comment]
VSTS only accepts cobertura-04.dtd format. It would be great if we can have it implemented

**Comment by libPhipp** [comment]
That would be great indeed. The only difference between Cobertura's [03.dtd](https://github.com/cobertura/web/blob/master/htdocs/xml/coverage-03.dtd) and the new [04.dtd](https://github.com/cobertura/web/blob/master/htdocs/xml/coverage-04.dtd) is in the <coverage> element. Five new required attributes were introduced:

lines-covered
lines-valid
branches-covered
branches-valid
complexity 

Does anyone know what information is expected in those attributes? Do we already have that elsewhere or may be at least the summands? Can we get the information from print_xml_report's parameter "covdata"?

**Comment by latk** [comment]
This issue seems to be quite important.

The meaning of these attributes can probably be derived from the Cobertura implementation itself. Their [XMLReport class](https://github.com/cobertura/cobertura/blob/master/cobertura/src/main/java/net/sourceforge/cobertura/reporting/xml/XMLReport.java) looks like a good starting point. Since they use the same code to generate reports for all DTDs, we can do the same.

Calculating cyclomatic complexity is clearly out of scope for gcovr, but I think the other parameters can be derived from the CoverageData objects.

If someone wants to take a go at this:

 0. Run the XML tests to verify that gcovr currently works: `python gcovr/tests/test_gcovr.py GcovrXml`
 1. Add the new required attributes to the report and use the 04.dtd.
 2. Re-run the XML tests. They should now fail due to the added attributes.
 3. For each failing tests, compare the actual report with the reference XML report. If there are no discrepancies other than the new attributes, replace the reference file with the new report.
 4. The tests should now pass again.
 5. Create a pull request to the master branch and mention this issue in the description.

Perhaps we also need to add a command line flag so that the DTD version can be selected explicitly.

**Comment by denniswjackson** [comment]
For those looking for complexity results, check out https://people.debian.org/~bame/pmccabe/download.html

**Comment by libPhipp** [comment]
I gave it a try and created a pull request for this issue. For the complexity value I have just copied the fixed '0.0' that we also have in the package- and class-elements for example. The tests didn't fail as expected, after my changes, as assertMatchesXmlBaseline() from pyutilib.th doesn't seem to compare doctype nor attributes.

**Comment by latk** [comment]
Thanks to @libPhipp's work in #186, we now use the newer Cobertura format.

Everyone: please test the current version with your setup (Jenkins plugins, VSTS, ...) and report any related problems in this thread.

To test this new feature, you must install gcovr directly from Github and not from PyPI. For example:

``` console
$ pip install git+https://github.com/gcovr/gcovr.git
```

**Comment by libPhipp** [comment]
Today I have tested the new state of the master branch in combination with VSTS and it works like a charm. The coverage statistics are now exported and also the html report can be included:
![coverage](https://user-images.githubusercontent.com/25852800/34685843-f63a813e-f4a9-11e7-8c5d-c3eba25b93c3.png)
