### ISSUE TITLE
Cannot analyse class under test in some cases

### ISSUE THREAD

**Issue by BelteZol** [gcovr/gcovr#172]
My tests are written with gtest framework and used CMake.

    ClassUnderTest.h:
    class ClassUnderTest
    {
    public:
        uint8_t Start(int in_a, int in_b);

        static uint8_t MethodToTest(int a, const uint8_t *b, uint32_t c);
    }

I have 2 test cases. One uses "TEST"s the other uses "TEST_F"s (a.k.a Test fixtures).

Test without Fixture:
 
     TestCase1.cpp:
     TEST (Test_Start, MethodToTest_test)
     {
         ClassUnderTest       TestObj;

         EXPECT_EQ(TestObj.Start(1,2),0xFF));
     }

Test with Fixture:
 
     TestCase2.cpp:
     class ClassUnderTest_Test : public ::testing::Test, public ClassUnderTest
     {
     public:
         virtual void SetUp();
         virtual void TearDown();

         bool TestCase2();
     };

    bool ClassUnderTest_Test :: TestCase2()
    {
        uint8_t retval;
        retval = ClassUnderTest::MethodToTest(1,2,3);

        return retval;
    }

    TEST_F( ClassUnderTest_Test , MethodToTest_test )
    {
        ASSERT_EQ( TestCase2(), true );
    }

In both cases ClassUnderTest.cpp.gcno is generated and inside the data seems valid, but then when I call gcovr in a following way:
python C:\Python27\Scripts\gcovr --html --html-details -o output-file-name.html

Only the coverage of TestCase1 found in the html report, TestCase2 coverage is not visible at ClassUnderTest.cpp.

**Comment by latk** [comment]
Hmm, that is certainly weird. I'm not entirely convinced this is a gcovr bug rather than some unexpected behaviour of some other part of the toolchain, so let's narrow the problem down. Here are a couple of suggestions:

 - Does the problem persist when the fixture doesn't inherit from the class under tests? Usually, the class under test would be a member of the fixture, not a base.

 - Does the problem persist when both test cases are part of the same compilation unit, i.e. the same file?

 - Can the problem be reproduced without gtest? I.e. replace the assertion macros with standard library asserts or `std::cerr << result` style code, remove the macros, and don't inherit from the Test class.

 - Does the problem persist when you inline the `ClassUnderTest.cpp` definitions into the header?

 - Does the class under test need two methods with those signatures of which one is static? Is either the static or non-static method sufficient? Is a signature `void method()` sufficient?

 - Can you create an example that can be executed without CMake, using manual compilation instead?

Thank you for starting to create a minimal example to explain your problem, but it's not quite specific enough that I could reproduce it and start debugging.

**Comment by latk** [comment]
This issue has not seen any progress in a while, so I am closing it for now. If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.
