### ISSUE TITLE
Absolute path for <source> in xml file

### ISSUE THREAD

**Issue by eDeviser** [gcovr/gcovr#177]
When using gcovr with `-x` an xml file is produced which can be used with jenkins plugin cobertura. This is really awesome! :-)

Well there is a little problem:

Using gcovr with `gcovr -r . -x` sets the source in the xml file to this: `<source>.<\source>`

Thus cobertura cannot find the sources because it is a relative path. It would be much better if gcovr would convert the path into an absolute one by using `realpath` which should be included to the most unix distributions.

For me I fixed this problem by calling gcovr in this way: "gcovr -r \`pwd\` -x"

**Comment by Flockstud** [comment]
I use gcovr with Jenkins as well, with no issues.
This is what I do:

```
cd <path-where-you-want-cobertura-to-find-the-xml-file>
<path-to-gcovr>/gcovr -r . -x
```
Hope that helps

**Comment by eDeviser** [comment]
Ok, I see the problem. My project setup is a little bit different from yours. I still believe that adapting the `-r` option to convert to an absolute path would be the better choice. Lets take a look to my project's structure:

The project is about the project's sourcecode and the library's source code:
/home/username/jenkins-home/myproject/projectCode/trunk
/home/username/jenkins-home/myproject/libraryCode/trunk


Jenkins starts by default in the projects directory which is in this case /home/username/jenkins-home/myproject
So the build command goes like this:
`cd projectCode/trunk`
`make all`
`gcovr -r . -x`

At this point the problem should be clear:
Cobertura's starting directory is the projects folder which is /home/username/jenkins-home/myproject
Gcovr's starting directory is /home/username/jenkins-home/myproject/projectCode/trunk
Thus all relative paths in the xml (generated by gcovr) cannot be found by cobertura.

As I already mentioned one solution is using the `pwd` as argument for `-r`  inside the call of gcovr.
As Flockstud mentioned doing a `cd` to the path-where-you-want-cobertura-to-find-the-xml-file (which is /home/username/jenkins-home/myproject) would also solve the problem.

For me it seems to be the better choice to adapting the `-r` option to convert to an absolute paths. 
I am, not the maintainer, It's your choice to accept this ticket or to reject it. ;-)

**Comment by wolf99** [comment]
This may be related to #171 ?

**Comment by latk** [comment]
> For me I fixed this problem by calling gcovr in this way: ``gcovr -r `pwd` -x``

And because you can use absolute paths if you want to, I don't think gcovr should output absolute paths by default. In particular, I see two problems:

 - In most cases, the absolute path is _irrelevant_. The coverage report should not concern itself with where in your file system the project was checked out.

 - This would complicate automated testing of gcovr. Because we use relative paths in the reports, the gcovr output is reproducible.

But I understand your frustration. The relationship between the pwd and the `--root` is a bit arcane. I find it frustrating that the reports often only show `.` or `..` as the directory, especially for nested projects where you need multiple reports. Perhaps this can be solved at some point in the future by making a distinction between the root as the base for relative paths and the root as a search path.
