### ISSUE TITLE
Clarify semantics for the --object-directory option

### ISSUE THREAD

**Issue by whart222** [gcovr/gcovr#18]
The gcovr code includes comments that indicates that the --object-directory option should be same one used by gcovr.  This is not obvious from the gcovr --help documentation.  Additionally, this option is not used by the get_datafiles() function to search for _.gc_ files.  That seems like a bug, but I'm not sure.

**Comment by latk** [comment]
There has been progress on the --object-directory option. Its semantics were studied and simplified in #280. Despite its name, there is no direct relationship between gcov's and gcovr's --object-directory options.

My long-term plan is to make search heuristics user-configurable rather than just offering the choice between standard and --object-directory heuristics.
