### ISSUE TITLE
Plan for the next release

### ISSUE THREAD

**Issue by mayeut** [gcovr/gcovr#202]
All is in the title, what's the plan for the next release ?

**Comment by latk** [comment]
My very rough roadmap is:

 - merge the dev branch (see #54, #55)
 - merge the HTML improvements (see #43)
 - perhaps some bug fixes, e.g for #191
 - rework the documentation (see https://github.com/gcovr/gcovr/pull/193#issuecomment-358604083)
 - update docs to reflect the changes since the last release
 - publish a 4.0 release, since there are some potentially breaking changes

Not all of that has to happen for the next release. There's actually a good argument for releasing right now: there are already lots of valuable bugfixes, e.g. for Windows usage. But I'd rather hold off for ~2 more months, so that the two large refactoring items (modularization and HTML templating) can be included.

I'd welcome any discussion on what should be included and what should be deferred. I'd also like to hear opinions (especially from users!) whether a there should be a release with the current bug fixes, before more refactoring is done. I can then create a milestone to track progress towards the release.

**Comment by mayeut** [comment]
IMHO there probably should be a release without major refactoring i.e. single script layout.
I don't think I'm the only one seeing `gcovr` used in a questionable way using the 'single script feature'. Having one official release without major refactoring will allow for users to get one last round of bug-fix while planning for the transition to a more pythonic way of dealing with `gcovr` installation.
An argument could be made that if 'single script feature' is to be used, a user might just pick any version in the repo history.

**Comment by goriy** [comment]
I agree with @mayeut that there should be a release before major refactoring.

Current stable release (3.3) simply doesn't work on Windows without manual patching. Current version from repository works fine (at least for my use cases) and I think that it's ready enough for minor release. 

I think that it would be great to have working stable version of traditional (i.e. single script) gcovr before going further.

**Comment by latk** [comment]
Ok, for a 3.4 release the checklist would be:

 - \* optional: merge any remaining bug fixes that should make it to this release
 - \* update guide/readme with bugfixes/improved features
 - \* update guide/readme with warning that installation is only recommended via pip (i.e., don't just put `scripts/` into the PATH)
 - \* update docs with current contributors
 - \* optional: fiddle around with website generation so that the readme is used as the landing page?
 - \* update the changelog
 - \* update copyright information to account for all the contributions since 2013 and from outside Sandia

Then, on a release branch:

 - \* bump version to 3.4 (see admin/release_checklist)
 - \* regenerate docs, incl. capturing new screenshots
 - push docs to website repo: https://github.com/gcovr/gcovr.github.com
 - merge to master, tag the release, and let Travis deploy to PyPI
 - \* :tada: hooray!

\* help welcome

I expect some minor complications around the documentation and website. But all of this can happen within 4 to 14 days, depending on how much help I'll get :)

**Comment by wolf99** [comment]
Depending on how much work it would require, I would be in favour of having the Windows bugs (à la #191) fixed for a 3.4 release. If the work is large however, or would become significantly more easy after or with a 4.0 then by all means leave it till then as the already completed bug-fixes are also important to get out.

**Comment by latk** [comment]
The Windows filter stuff discussed in #191 needs more thought and
experimentation. I don't have that kind of time until the end of the
month. So unless someone volunteers to work on this over the weekend,
I'd rather defer this.

Waiting until 4.x isn't necessarily bad. It allows us to

 - make improvements that may not be backwards-compatible, and
 - build a better understanding of the code base by refactoring it first.

How filters should work also affects how file names should be handled
throughout the code. And that affects nearly everything. Once the code
is more modularized and different components have clearer interfaces,
it will be easier to make these changes one step at a time.

**Comment by latk** [comment]
I have published `3.4rc1`, i.e. a pre-release. You can see it on

 - https://pypi.python.org/pypi/gcovr/3.4rc1
- https://pypi.org/project/gcovr/3.4rc1/

Please verify that you can install this version from pypi, e.g.

    pip install gcovr==3.4rc1

If someone can manually confirm on Windows, I will continue with the proper release.

The readme is now rendered fine, and looks like a great improvement.
One minor hitch is that the screenshots are not rendered on pypi, as they depend on relative paths. I think that can be solved by rewriting the URLs when loading the description in the setup.py. But that is a cosmetic problem, and will not block the 3.4 release.

**Comment by wolf99** [comment]
I may have time to try this on a windows box over the weekend - will report back if I do :+1:

**Comment by Anketell** [comment]
When updating docs, could you please also specify the gcc versions that you tested against.

This is important for users to understand gcc version compatibility. 

Thanking you in advance.

**Comment by latk** [comment]
@Anketell In principle, all reasonably modern versions of GCC and Clang are supported. If there is a problem, that is a bug (e.g as your #179 might be, if you can add instructions to reproduce).

As this was a small change, I updated the User Guide in 1980aaf058907bb185d783b6ca2568cddea61018 to reflect the tested environment more clearly:

> Which environments does ``gcovr`` support?
>
> -   Python: 2.7+ and 3.4+. Python 2.6 is supported on a best-effort basis.
> The automated tests run on CPython 2.7, 3.4, and 3.5, and PyPy 2.7 and 3.5.
> -   Operating System: Linux, Windows, and macOS.
 > The automated tests run on Ubuntu 14.04 and Windows Server 2012.
> -   Compiler: GCC and Clang.
> The automated tests run on GCC 5.

**Comment by Anketell** [comment]
@latk regrettably I could find no rhyme nor reason for the issues that I saw so could not distil an example.

If something specific comes to light, I will let you know.

**Comment by wolf99** [comment]
On windows 7 with Python 3.6.4, the rc1 mentioned above installs fine and in cmd.exe (administrator mode as my python install is in Program Files (x86) as part f MS Visual Studio) and outputs as shown:

````bash
C:\WINDOWS\system32>python "C:\Program Files (x86)\Microsoft Visual Studio\Shar
d\Python36_64\Scripts\gcovr"
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: .
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
------------------------------------------------------------------------------
TOTAL                                          0       0    --%
------------------------------------------------------------------------------
````

So everything seems to be working in that regard. Unfortunately I haven't had time to do further testing as I had planned over the weekend :confused:

**Comment by latk** [comment]
We did it! 3.4 is out now. A very big thank you to everyone who contributed to this release, whether through pull requests, through discussions, or by raising issues. I was positively surprised by these contributions :)

My intention for the next few weeks is to work on modularization, then see which issues can be resolved next. Of course, something else will probably crop up, so I'll let myself be surprised :)

If 3.4 introduced any regressions or has any critical problems (like “filters won't work on Windows” was), I'll of course try to do a 3.5 or 3.4.1 release. Otherwise, I'd prefer to delay smaller problems in favour of a 4.0 release with deeper changes.

**Comment by wolf99** [comment]
Well done @latk, your work on this is very appreciated by those of us that like and use this tool!
