### ISSUE TITLE
Add coverage report for gcovr

### ISSUE THREAD

**Issue by mayeut** [gcovr/gcovr#216]
IMHO, gcovr is missing a public coverage report on CI builds.

It would allow:
- To track coverage progress when adding tests, before refactoring gcovr
- To make sure PR are well tested and reject PR that have an insufficient diff coverage
- For everyone to know what's tested

There are at least 2 service providers that allow to get a report on each CI build that I know of:
- codecov
- coveralls

Here's a sample output using codecov: https://codecov.io/gh/mayeut/gcovr/branch/module-coverage

**Comment by latk** [comment]
Absolutely! I'd like this very much. I'm not familiar with any particular provider so I'll leave that choice at your discretion. If in doubt, we can do both :) Please let me know If I should create an account or something.

I'm not sure if any of these services can integrate with GH as a pull request check (like Travis and Appveyor do), but even having informational code coverage around somewhere else is going to be quite useful. My main motivation for having coverage is that I can see which behaviour is not tested (e.g. the `--exclude-directories` option) because those parts are possibly broken and require further scrutiny.

If you already know how to configure the coverage collection, a PR or a pointer to the instructions would be welcome.

**Comment by mayeut** [comment]
I know that [codecov](https://codecov.io) does indeed integrate as a pull request check. I don't know about [coveralls](https://coveralls.io).

In order to enable [codecov](https://codecov.io), you just need to login using your GitHub account and add the `gcovr` repository. I don't know how it works with organization accounts though.
Once this is done, I can create a Pull Request using my existing branch doing CI coverage on my fork.

**Comment by latk** [comment]
OK, I've activated codecov on the gcovr/gcovr repo.
