### ISSUE TITLE
Regression on filtering between gcovr 3.4 and gcovr 3.3

### ISSUE THREAD

**Issue by mayeut** [gcovr/gcovr#220]
The way filtering works has changed between 3.3 and 3.4, since commit 90589892b9f32d811bedca3008d1e8960389faf2

Feel free to mark as won't fix but just thought I'd report the regression I saw.
The way filtering works is properly documented in the guide for 3.4
The changelog only says `Fix to support filtering with absolute paths.`

Sample layout:
```
root
|-extern
|  |- ...
|- lib
|  |- ...
```
Run with `gcovr -r ../root -e extern` from the `lib` subfolder:
`extern` was excluded with gcovr 3.3. It's not anymore with gcvor 3.4

**Comment by latk** [comment]
This is by design. The current, known-broken design. Filters are normalized relative to the current working directory, not relative to the root. Filters are matched against the absolute path of a file. Possible workarounds (untested):

 - use a relative path for the exclude filter: `-e ../extern`. This should be compiled to an absolute filter `/your-project/root/extern`. Not supported on Windows.
 - use an absolute filter to exclude any files under any "extern" directory: `-e '/.*/extern'`. Not supported on Windows.

The only way to do this on all platforms incl. Windows is to run gcovr in the root (`-r .`). Then, the original exclude filter `-e extern` should work. Of course, this may introduce other problems, such as connecting coverage data and source files :/

In any case, this is another use case that's relevant to filter design, as discussed in #191. Thank you for reporting this.

**Comment by latk** [comment]
I've been thinking about this a bit more. If filters are not by default relative to the current working directory, they will be terribly unintuitive. So this design cannot be changed reasonably.

Instead, there might be fixable root problems:

 - “I want gcovr to accept my filter as a regex, without trying to turn it into a path.” This would require either

    - a flag that changes interpretation of all filters, or 
    - a change so that filter regexes are not first abspath()'d, but instead are matched against relative paths – this is very difficult, or
    - some syntax to mark a filter as a pure regex. To preserve backwards compatibility, this should be syntax that is illegal for a regex. A leading quantifier (one of `*+?`) would do the trick: `gcovr -e +extern`? A plus has the advantage of not looking like a glob pattern, e.g. `gcovr -e *extern`.

 - “I want to run gcovr from the source root, but have to run it from the build directory so that all files are found correctly.” I.e. all these CMake/OOS-related problems.

    This requires further thought regarding the `gcovr.gcov` path handling, which is still very opaque to me. I'm tempted to add a `--build-dir` flag that processes gcovr as if invoked from that build dir, but I strongly assume this is mostly redundant in connection with the existing options.

Any thoughts?

One thing that surprises me about the shown project layout is that gcovr is invoked from a source subdirectory, the root points to the source root, but other source subdirectories are excluded. That seems nonsensical to me. Why wouldn't you run from the source root or restrict the root to the lib subdirectory?

**Comment by barthoukes** [comment]
Windows uses the backward slash C:\ and drive letters. Gcovr was not made for this inferior operating system. However, since I am forced to work with Windows 10 I made a temporary solution until the GCOVR people are finished discussing the solution of \\ and /  ... feel free to download my gcovr variation from https://github.com/barthoukes/gcovr . You only need the file gcovr itself (python script). Please run the tool from your output directory. I will remove this version when the real one is repaired.

**Comment by latk** [comment]
The filter design has been changed in pr #257, which largely keeps the behaviour from 3.4. However, the filter regexes are no longer munged via `abspath()`. If a regex looks like an absolute path, it will be matched against an absolute path. Otherwise, it will be matched to a path that is relative to the current directory (not the root directory!).
