### ISSUE TITLE
gcov segfaults but gcovr ignores this fact

### ISSUE THREAD

**Issue by mgerhardy** [gcovr/gcovr#254]
the gcov call produced a segfault and the exit code of that particular call wasn't taken into account.

**Comment by latk** [comment]
Thank you for this report! It seems that we are indeed ignoring the gcov exit code  (see the subprocess call in [`gcovr.gcov`](https://github.com/gcovr/gcovr/blob/e692552e76ed28a4d2cfc38d5b962c4b4f6142cd/gcovr/gcov.py#L653)). However, gcovr works in a way that calls to `gcov` may in fact fail if we are in the wrong directory. So we can't just abort on non-zero exit codes.

We do however collect parts of the stderr output from gcov and display it if no possible call succeeded. We could perhaps synthesize an error message for non-zero exit codes, if gcov doesn't provide any error messages on its own. According to the subprocess docs, a negative return code indicates that the process was terminated by signal (such as SIGSEV). We could treat those as a hard failure.

What would you suggest should gcovr do?

But please understand that gcovr and gcov are different projects. If you managed to provoke a segfault on a supported version of gcov through normal usage, that would be a GCC bug.

**Comment by loximann** [comment]
In summary, it would be nice that gcovr warns that something went wrong.

The main issue I had is that all of a sudden coverage went down, and I was trying to figure out why for a long time. Tottally puzzled, I gave a try to lcov, which threw this
```
...
Processing ...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
geninfo: ERROR: GCOV failed for ...!
```
Which put me on the right track: it's not my code, it's gcov that's crashing. With --ignore-errors gcov the ERROR is reported as WARNING and lcov continues processing files.

**Comment by latk** [comment]
Thank you @loximann for reminding me of this issue :) You are absolutely right that this is a bad failure mode.

Unfortunately I'm swamped with other stuff to do and will not be able to address this issue during this year. If you or someone else would like to take a shot at this problem, that would be quite welcome. (I'll gladly assist via our Gitter chat.)

What has changed since the last time I looked at this, is that gcovr no longer supports Python 2.6 and we can therefore use better subprocess APIs (?). The current gcov error management strategy also looks dubious, as we only show stderr if no gcov invocation succeeded and the stderr contained a message like “Cannot open source file”. This should likely be flipped around: stderr should be shown and non-zero exit codes should be fatal, unless the problem appears ignorable.

**Comment by loximann** [comment]
I will look into this!
