### ISSUE TITLE
gcovr does not seem to respect "--exclude-directories"

### ISSUE THREAD

**Issue by gocarlos** [gcovr/gcovr#258]
When building this [hello world example](https://github.com/gocarlos/gtest-demo-gitlab)

I get this: 
![image](https://user-images.githubusercontent.com/1331762/40598356-859d2f06-6247-11e8-9612-a059107c3f4e.png)

even though I call gcovr in the build directory with `gcovr -r .. --exclude-directories=external --html -o coverage.html`

## Full instructions to see the issue: 
```
git clone --recursive https://github.com/gocarlos/gtest-demo-gitlab.git
#!/bin/bash
rm -rf _build
mkdir _build
cd _build
cmake ..
cmake --build .
ctest
gcovr -r .. --exclude-directories=external --html -o coverage.html
```

Also tried 
gcovr -r .. --exclude-directories="^external*" --html -o coverage.html
gcovr -r .. --exclude-directories="../external" --html -o coverage.html

**Comment by latk** [comment]
I think you're right that --exclude-directories is broken, but for a
different reason: that flag is supposed to exclude directories while
searching for raw coverage data. It doesn't directly exclude directories
from the reports.

For your use case, a plain --exclude filter should be sufficient:

    cd _build; gcovr -r .. -e ../external/ --html -o coverage.html

Did that work?

**Comment by gocarlos** [comment]
yeap, that did the trick, thanks

**Comment by pietryna** [comment]
@latk I've encountered similar issue. When I specify -e ${CMAKE_SOURCE_DIR}/../sth (expanding to C:\Users\one\two\..\sth) it does not work, but when I specify direct path (C:\Users\one\sth) it's correctly excluded.

gcov version 13.1.0
gcovr 6.0

**Comment by latk** [comment]
@pietryna All filtering options like `--exclude` take a *filter pattern*, not a *path*¹. These filters are not normalized, but turned directly into a regex. In a regex, something like `../` means "any two characters followed by a slash". And `\` backslash characters indicate special escapes, not a folder. The only "magic" gcovr does is to guess whether this filter pattern is intended to match an absolute path like `C:/foo/bar` or a relative path like `subdirectory`.

¹ the `--root` argument and positional `search_path` parameters are the only exceptions

See *Using Filters* in the Gcovr User Guide for details: https://gcovr.com/en/6.0/guide/filters.html

Unfortunately, this means that you probably can't just take CMake variables and use them as a filter on Windows. But the good news is that you can probably use a pattern for a relative path instead. I'm not entirely sure how you're running gcovr, but one of these patterns might work:

* `-e sth`
* `-e '\.\./sth'` (note backslashes so that `.` matches a literal dot in the relative path. How to escape the backslashes depends on the shell. Enclosing the patterns in single quotes is appropriate for Bash and other POSIX shells. Maybe you don't need any escapes at all?)

**Comment by pietryna** [comment]
@latk Thanks for the answer. I'm modifying project as I got so I did not go that deep. They used more lile paths instead of regexes (where full paths has matched fortunatelly). However escaping dots did not work but I will not dig into this as we do not have time :|
