### ISSUE TITLE
Support setup.cfg when using gcovr in Python + C projects

### ISSUE THREAD

**Issue by stadelmanma** [gcovr/gcovr#260]
First off thank you for this tool, it is a great alternative to lcov. The project I am currently using it on is a mix of Python and C extension modules. Would it be possible to support configuration via the "semi-standard" `setup.cfg` file as an alternative to just command line options? 

Secondly, this is beyond the scope of this particular issue but relevant to supporting Python C extensions better. An issue with using gcov on Python C extensions is is that I can't get the setup.py script to **not** recompile source files shared between extension modules that are already an object file. As a result that the timestamps between the `*.gcno` and `*.gcda` files can be mismatched and gcov emits a warning.  Maybe I'm missing the mark and there is a way to configure `setup.py build_ext` to do things more like `make`? (if so ignore this portion completely)

This is easily fixed using the code snippet below (where files have been globbed appropriately)
```Python
# gcda/gcno header format: [int32:magic int32:version int32:stamp]

# collect a timestamp from the first notes file to replicate
with open(gcno_files[0], 'rb') as fp:
    fp.seek(8)
    stamp = fp.read(4)

# replace stamp in header across all files to prevent errors
for file in gcno_files + gcda_files:
    with open(file, 'r+b') as fp:
        fp.seek(8)
        fp.write(stamp)
```  
However I don't know how you and your team feel about adding language specific logic into the utility. Supporting standard config files is one thing, but I completely understand the desire to let users deal with hacks like the one above.

**Comment by latk** [comment]
I appreciate your kind words :)

### Configuration files

Config files are not yet implemented. They were discussed in #229 (incl. a proof of concept), but that code has not yet been merged. Config files are difficult because:

- we do not want to duplicate all the validation logic from argparse
- we have to think about default file locations and precedence of arguments
- we have to choose a config file format that supports multiple entries per key, e.g. to model the `--exclude` flag. This seems to rule out setup.cfg and any `configparser` based config files.

I really hope that proper config files will be implemented at some point, but I don't have the time to pick up the work myself. (hint hint)

As a workaround you can wrap gcovr in a shell script that adds your required options, e.g.:

``` bash
#!/bin/sh
mkdir -p coverage
exec gcovr --filter src/ --output coverage/index.html --html-details "$@"
```

### Usage with Python C extensions

I'm not sufficiently familiar with the Python toolchain to help you. The workaround you've found is terribly hacky, but if it works, it works :)

Please understand that gcovr is a tool primarily for C/C++ development that happens to be written in Python, and not directly a utility for Python development. I'm not totally opposed to implementing build-system specific improvements, but so far I don't see any use cases. Instead of adding more features I'd rather add a chapter to the user guide.

I will not add that workaround to gcovr itself. Those warnings could indicate a real problem and I don't want to hide that from users (we are already swallowing too much of the gcov error messages in an attempt to find the gcov file locations). The gcov binary formats are also not stable, and I don't think the same hack will work across GCC 4–8 and Clang.

Again, it may be best to write your own script that adds these features.

If you manage to collect Python C extension coverage with gcovr (in a less hacky way), that would be a great blog post and/or addition to our docs, so please report back :)

**Comment by stadelmanma** [comment]
Re: Config Files
----
I have a feeling the pytest module might be a good place to draw inspiration from since they have already solved some (maybe all?) of the problems mentioned in the linked issue. Although, they are python environment specific which this tool is not so there is that to take into consideration.

This is something I might look into further when time allows, since I am  fan of config files over shell scripts due to their inherent portability.

Usage with Python C extensions
----
And no offense taken, Python is most certainly an after thought when it comes to tools like gcov; that is evident from the sparse documentation on the web. The hack is due to how I am setting up my C extensions. If C files weren't shared between modules then it wouldn't be necessary and perhaps that means I'm acting too much like a C programmer. 

The problem is not on Gcovr's end, it works perfectly in regard to collecting and displaying the coverage results, so no new documentation needed. 

<hr/>

I'm going to close this issue and do any follow up discussion on #229 if/when I am able to map anything out on that front. Thank you for the very prompt response!

Cheers,
Matt

**Comment by stadelmanma** [comment]
@latk apologies for commenting on a closed issue, but it appears I was asking the wrong questions in regards to getting setup.py to properly cooperate with gcov yesterday. 

While the logic in distutils used to build extensions is more or less "fixed" other external tools can fill the void, notably `ccache` for MacOS/Unix and according to [this SO post](https://stackoverflow.com/a/18992595) [clcache](https://github.com/frerich/clcache) may work on Windows but I have no way to test that.

Below is the script I use to generate code coverage, it uses `gcovr` by default and falls back to regular `gcov` when it's not available (I tend to omit installing gcovr on temporary docker containers). You mentioned adding something the docs about this use case but I don't immediately see a particularly good location in any of the existing files. Perhaps `guide.rst`? Unless you think this is too language/build system specific to go there. Either way I'll gladly submit a PR and put it where ever you prefer if you'd like to incorporate it.

```python
#!/usr/bin/env python
r"""
Processes the coverage data generated for the C extensions using gcov.

The extension should have been compiled with the -coverage flag which can
be applied with `export CFLAGS="-coverage"` prior to building the extension
modules. If you need to rebuild everything with the coverage flag use the
command `python setup.py build_ext --inplace -f` or remove the build files
under the build directory.

Additionally, Python will rebuild any shared source files regardless if
they have been compiled already or not. Using a tool such as `ccache` fixes
this problem. The source cache program can be applied to gcc using
`export CC="ccache gcc"`. Otherwise gcov will throw an error for "old"
objects and coverage data will be inaccurate.

Coverage collection example:
---
export CFLAGS="-coverage"
export CC="ccache gcc"
rm -rf build
python setup.py build_ext --inplace
pytest
./bin/gcov.py
---
"""
from glob import glob
import os
from subprocess import run
from shutil import move, rmtree


PROJ_DIR = os.path.realpath(os.path.dirname(os.path.dirname(__file__)))
COVERAGE_DIR = os.path.join(PROJ_DIR, 'coverage')
GCOV_CMD = [
    'gcov',
    '-pbc'
]
GCOVR_INDEX_FILE = os.path.join(COVERAGE_DIR, 'index.html')
GCOVR_CMD = [
    'gcovr',
    '--print-summary',
    '--html',
    '--html-details',
    '--keep',
    '--filter', 'src/cpl_tools',
    '-o', GCOVR_INDEX_FILE
]


# collect all of the notes files
build_dir = os.path.join(os.path.realpath('build'), 'temp.*')
gcno_files = glob(os.path.join(build_dir, '**', '*.gcno'), recursive=True)


# Create or recreate coverage directory
try:
    os.mkdir(COVERAGE_DIR)
except FileExistsError:
    rmtree(COVERAGE_DIR)
    os.mkdir(COVERAGE_DIR)


# Run gcov or gcovr to calculate coverage totals
try:
    run(GCOVR_CMD, check=True)
    print('View HTML report at: ' + GCOVR_INDEX_FILE)
except FileNotFoundError as err:
    run(GCOV_CMD + gcno_files, check=True)
    print(err)
    print('"gcovr" is not installed no HTML report will be generated.')


# Reconstruct source directory structure and move gcov files
for file_name in glob('*.gcov'):
    abs_path = file_name.replace('#', os.path.sep)
    # Check if path is inside project's directory
    if PROJ_DIR not in abs_path:
        os.remove(file_name)
        continue
    rel_path = os.path.relpath(abs_path, PROJ_DIR)
    # create directories if needed and move file
    outfile = os.path.join(COVERAGE_DIR, rel_path)
    os.makedirs(os.path.dirname(outfile), exist_ok=True)
    move(file_name, outfile)

```

**Comment by latk** [comment]
This looks interesting! Ideally we can add a new cookbook page to the docs. I'd appreciate a PR that massages your findings in this issue into a few paragraphs. Please let me know if I can assist in any way.
