### ISSUE TITLE
Unrecognized gcovr output

### ISSUE THREAD

**Issue by Spacetown** [gcovr/gcovr#275]
With mingw 4.5.0 and gcovr 4.1.0 I get following message:
```
(WARNING) Unrecognized GCOV output for t:\frdcc_pa_test\testumgebung\KomponentenMake\development\source\Function\Main.cpp
	      $$$$$:  215-block  0

	      $$$$$:  263-block  0

	      $$$$$:  275-block  0

	      $$$$$:  296-block  0

	This is indicative of a gcov output parse error.
	Please report this to the gcovr developers
	at <https://github.com/gcovr/gcovr/issues>.
```
(https://github.com/gcovr/gcovr/files/2262477/unittest.Main.gcda.Main.cpp.zip)

**Comment by latk** [comment]
These markers are created by `gcov -a`, which outputs information about all “basic blocks”. This is related to branch coverage. Gcovr does not use the `-a` option and its parser is currently unable to handle these markers, which occasionally leads to problems if you are using existing gcov files (via `gcovr -g`). It may also be that GCC 4.5 did not yet have the -a option and would always output these markers?

The corresponding parsing code is in gcovr/gcov.py in the `GcovParser` class. Adding support for basic blocks would require:

 - recognizing `$$$$$` and `%%%%%` markers for uncovered blocks. This info can be discarded because info about uncovered branches can be taken from branch coverage.
 - recognizing block summary lines. They look like `<count>: <lineno>-block <blockno>`, whereas normal code lines look like `<count>: <lineno>:<code>`. Again, these can be discarded.

In the far future gcovr might use per-block coverage data to show control flow within statements in the HTML report (e.g. from `&&, ||, ?:` operators or from exceptions)

**Comment by latk** [comment]
See also #82

**Comment by Spacetown** [comment]
Since gcovr 5.1, gcov files with block coverage information can be parsed successfully, though the information is not included in any coverage reports.
