### ISSUE TITLE
Configure tab size for HTML report

### ISSUE THREAD

**Issue by itavero** [gcovr/gcovr#277]
At work we use hard tabs (so no spaces) in our code.
It would be nice if we could configure the CSS `tab-size` property when calling Gcovr.
That way we can set it to `3` (in our case) and have the HTML reports be aligned properly.

In most browser it defaults to `8`, but I would say a default of `4` or even `2` would also make a lot of sense (that are defaults used by a lot of IDEs).

**Comment by latk** [comment]
Thanks for the idea! I won't add an option specifically for tab size, but I too want more configurable CSS.

Currently, the CSS is inlined into the HTML. That's unnecessary duplication (70% of the gcovr code base consists of HTML test files…) and makes the reports difficult to style.

I'd like to see command line options so that:

 - the CSS can be written into a separate file
 - the HTML reports can reference an external file (so that the external CSS is shared by all reports)

This would allow you to provide a patched CSS file instead. It would also make the gcovr test suite much smaller. Finally, external CSS might help with the perpetual Jenkins-CSP problems (#125).

I am not sure how these options should be called and how they interact, so that all of the following cases are covered:

 - the CSS is inlined into each HTML report – what is currently being done
 - the CSS is written to an separate file that is linked by each HTML report
 - external CSS is provided that is linked by each HTML report. Gcovr's CSS isn't used.
 - CSS is written into a separate file **and** external CSS is provided. The external CSS is linked by each HTML report. The external CSS can `@import` gcovr's CSS file to override its contents.

Would you like to try implementing this? I'm afraid the `gcovr/html_generator.py` code is a bit of a mess right now, but only the `data['CSS']` variable plus the I/O should be relevant here.

**Comment by itavero** [comment]
That also sounds like a very good suggestion. My calendar is full for the next few weeks, but I'll see if I can find some time after that.

**Comment by Spacetown** [comment]
Found this old issue.
Now the CSS is an external file and this enhancement can be implemented quite easy.
If an external file is given should the the file be copied beside the HTML, the given path added as it is or changed to an absolute path? There could also be an additional parameter to control what to do.

**Comment by latk** [comment]
Resolved by #377: CSS tab size can now be specified via `--html-tab-size` option. Inclusion of external CSS hasn't been implemented yet.
