### ISSUE TITLE
Add option to output as lcov .info format

### ISSUE THREAD

**Issue by RPGillespie6** [gcovr/gcovr#288]
I like how gcovr is faster than lcov, but I don't like how gcovr's html output is one monstrously long list of source files. I prefer lcov's drill down approach. I would like to implement the ability to output as lcov's `.info` files so I can use `genhtml` to generate the html report. Contribution guide says to discuss enhancements as issues first.

Thoughts?

**Comment by latk** [comment]
Compare also #160: nested HTML reports could be implemented in gcovr itself, but the current HTML code is a bit messed up. Sooner or later this will happen. You'll have to decide whether it's easier to implement LCOV's format or to update gcovr's report generator.

I have no fundamental objection to adding interop with LCOV's info format, e.g. using something like an `--lcov` output flag. However, I'll end up being the one maintaining this so I'd tend to be cautious with flashy new features. Therefore:

 - Please make sure the LCOV info format is sufficiently stable and documented before implementing it
 - Please add test cases for this output format, in addition to the txt/xml/html output types already tested.
 - If you need preliminary work before you can implement another report generator, please submit those as smallish PRs in advance. You are also welcome to open a WIP pull request as soon as you have something reviewable.
 - I'd welcome if you could broadcast what you're about to do in the Gitter chatroom (https://gitter.im/gcovr/gcovr) so that I can assist or intervene as appropriate. Also a good place for smallish questions regarding internals.

Go for it!

**Comment by RPGillespie6** [comment]
Unless gcovr is extremely fast, the effort to implement this doesn't save much vs. just using lcov. I'll close for now and re-open down the road if viable.
