### ISSUE TITLE
Speed up gcovr

### ISSUE THREAD

**Issue by RPGillespie6** [gcovr/gcovr#289]
Gcovr is way too slow.

For example, if I do the following:

`find . -name *.gcda | grep -v "\.test"` I get a list of ~200 files in 100 ms.

If I then spawn 8 gcov processes in parallel like such:
```
gcov -i <25 files> &
gcov -i <next 25 files> &
gcov -i <next 25 files> &
gcov -i <next 25 files> &
gcov -i <next 25 files> &
gcov -i <next 25 files> &
gcov -i <next 25 files> &
gcov -i <all remaining files> &
```

It takes 800 milliseconds to complete, bringing total execution time to 900 ms. All that remains is to process the .gcov files. On my system, there are 550 gcov files generated, but the vast majority should be ignored (system headers) so I doubt that should take more than a second.

When I use `gcovr -j8 -e '\.test.*$' --exclude-directories '/usr/include'` it takes >30 seconds to run to completion. I suspect that the reason `gcovr` is so slow is that it is forking 1 gcov per gcda file which in my case ends up being more than 200 forks.

I propose a slight change in architecture so that gcovr operates like this:
1) Get list of all gcda files
2) iterate through list once, filtering files according to user input arriving at T files remaining
3) Spawn N gcov processes (in my case 8), each getting T/N files as arguments (in my case 25 files)
4) Process gcov files as normal (also in parallel), ignoring ones that were specified by user filters

I was actually thinking of making my own coverage utility to do this, but in I am willing to implement this here to avoid creating YAGW (yet another gcov wrapper). Contribution guide says to discuss enhancements as issues first.

Thoughts?

**Comment by latk** [comment]
There are a number of problems with being fast, most importantly that the coverage reports should also be correct. And that is surprisingly difficult.

 - There is one .gcda file per compilation unit, which may include coverage date for many different source files (headers). We therefore have to run gcov over it before we can apply _any_ filters (the exception being --exclude-directories, which prevents some directories from being _searched_ for .gcda files – your above usage is incorrect).

 - The gcov utility must be invoked from the same directory where the compiler was invoked from. This information is _not known_ to gcovr. Instead, we try out multiple promising directories and use the first one that doesn't obviously fail. This heuristic approach is known to be incorrect (cf #271) and slow, as there will typically be >1 gcov invocation per .gcda file.

 - The `-j` parallelization is sometimes able to compensate for this overhead by running multiple gcov processes in parallel. But only one gcov process can be run per directory (so that no .gcov files are overwritten) which limits its effect. Typically, `-j` will end up being _slower_ than the default. Parsing can't be parallelized because of Python's Global Interpreter Lock.

 - The current set of heuristics makes it impossible to process multiple .gcda files in one gcov call.

Note that e.g. the grcov tool is able to run much faster because it doesn't need the heuristics. It is based on gcov's intermediate format rather than the human readable reports. For the human-readable reports, gcov needs to find the original source code in addition to the gcda/gcno files, therefore the gcov invocation directory matters. Gcovr always needs to parse the source code in order to handle coverage exclusion markers, so little would be won if we switch to the intermediate format (which is deprecated anyway as gcov will switch to a JSON-based intermediate format).

While important, this issue is not actionable. I'm therefore closing it for now. I expect that we will be able to get better performance when the heuristics are corrected (#271) or when the GCC 9.1 JSON format is used rather than the human readable gcov formats (#282).

**Comment by RPGillespie6** [comment]
> There are a number of problems with being fast, most importantly that the coverage reports should also be correct. And that is surprisingly difficult.

Correctness is in the eye of the beholder. Developer should have overriding authority to decide what is correct and what is not IMO, not gcovr.

> There is one .gcda file per compilation unit, which may include coverage date for many different source files (headers). We therefore have to run gcov over it before we can apply any filters

How is excluding gcdas explicitly any different from excluding entire directories from being searched? If I as the developer know that gcda files containing `.test` do not contain coverage information that I care about, who is gcovr to say no?

> The gcov utility must be invoked from the same directory where the compiler was invoked from. This information is not known to gcovr.

It's known to me. We use CMake, and all files are compiled from the build directory. And actually it doesn't matter because CMake uses absolute paths for all include paths and source files, so gcov can be invoked anywhere I believe. At any rate I could pass this information to gcovr via CLI.

> The current set of heuristics makes it impossible to process multiple .gcda files in one gcov call.

Seems like if you setup your project correctly, it's possible to get around all the issues you mentioned and get extremely fast coverage reports. The the entire reason I'm looking for alternatives to lcov. It costs 1 minute per build to generate a coverage report when it could be costing 1 second.

**Comment by latk** [comment]
Thank you @RPGillespie6 for trying to get faster coverage reports. After all, that would save a lot of time for a lot of people. But if getting from 1m reports to 1s reports takes 1 month of research & development, that is time I cannot donate.

Re excluding gcda files early:

You could implement a gcda-based filter, similar to the existing --exclude-directories. Since that name has been confusing, I'd deprecate that name and use --search-exclude/--search-directory-exclude. 

However, the name of the gcda file is typically the same as the object file, and is as such chosen by the build system – which may remove lots of relevant information. And in most cases you don't want to exclude any coverage data. In particular, gcdas for test files may contain coverage of headers being tested.

Re communicating build system info to gcovr:

I'd love a way to do that, but don't know how. The --object-directory flag was originally intended as something like this, but turned out to just be a different set of (flawed) heuristics. If you can come up with a sensible way, I'd love to hear it! Even if it just addresses a subset of practical configurations. I'd also be open to heuristics that start by searching the source files rather than the gcda files, which could make it easier to tell gcovr where the compiler was invoked.

What is not going to happen is that gcovr starts detecting build systems or parsing CMakeLists.txt files, that would be way to much complexity. Similarly, gcovr will never mandate a specific project layout. Correctness in this sense means being able to deal with anything that GCC might do, regardless of build system.

**Comment by RPGillespie6** [comment]
> You could implement a gcda-based filter, similar to the existing --exclude-directories. Since that name has been confusing, I'd deprecate that name and use --search-exclude/--search-directory-exclude.

True, but after running a few experiments, this only saves you a couple seconds (depending on how many you filter). By far the biggest timesaver is invoking a single gcov and passing many gcdas to it instead of 1:1 gcov:gcda, which, if I understand correctly, can't be done because the gcdas may have been compiled from different locations.

> Similarly, gcovr will never mandate a specific project layout. Correctness in this sense means being able to deal with anything that GCC might do, regardless of build system.

In that case I may just build my own opinionated alternative to lcov. Either that or introduce a `--cmake` flag that lets gcovr make a bunch of assumptions about the project in exchange for a small risk of correctness compromised. When you can make assumptions about the target project you can really simplify things. For example, knowing it's a CMake project that was built using out-of-source builds lets you assume the location of where compiler was invoked.

**Comment by latk** [comment]
> For example, knowing it's a CMake project that was built using out-of-source builds lets you assume the location of where compiler was invoked

If you can describe to me a CMake heuristic in pseudocode, that could be implemented for gcovr. Conceptually, we need a function `compiler_dir = heuristic(gcda_or_gcno_file, cwd, root_dir, any_other_data_you_need)`. If you implement your own tool that would be also fine, because I can then take a peek there :) (assuming you open-source it)

In the past I wanted to avoid build-system specific configuration because gcovr should “just work”, but that's really difficult to pull off. As a compromise, I'm willing to explicitly spell out heuristics and let the users choose/override one. E.g. `--heuristic in-source` or `--heuristic 'path /gcc/called/here'` or `--heuristic 'cmake-oos ./build-dir'` – though I'll have to think more about a proper user interface that can encode things like fallbacks/alternatives. Such a system would also be great to evolve default heuristics while maintaining some amount of backwards compatibility.

**Comment by RPGillespie6** [comment]
In the case of 99% of CMake use cases, `compiler_dir = root_dir` for files people are going to care about. The cases where compiler is not invoked from root_dir is when building [external projects](https://cmake.org/cmake/help/latest/module/ExternalProject.html#id1). However, I would argue that it is reasonable to add a constraint that external project coverage is not supported. For exapmle, you might be building OpenSSL as an external project... and that should have its own testing and coverage process IMO. 

For example, if the directory layout looks like this:

```
project
    build/
    src/
    test/
    ext/
```
The root_dir is going to be `build/` and the compiler_dir is going to be `build/`. 

I think I can hack together a small (<200 lines) python script to achieve this for our current cmake projects, I'll let you know so you can take a peek (and yes, it will be open source).

**Comment by RPGillespie6** [comment]
Here's a prototype python program I've written that chews through all gcda files on in my project in 500 ms.

I plan on adding it here: https://github.com/RPGillespie6/fastcov

But here's a sneak peek:

```
#!/usr/bin/env python3
"""
    Author: Bryan Gillespie

    A drop in replacement for lcov
"""

import os
import argparse
import subprocess
import multiprocessing

MINIMUM_GCOV = (7,1,0)

def chunks(l, n):
    """Yield successive n-sized chunks from l."""
    for i in range(0, len(l), n):
        yield l[i:i + n]

def getGcovVersion(gcov):
    p = subprocess.Popen([gcov, "-v"], stdout=subprocess.PIPE)
    output = p.communicate()[0].decode('UTF-8')
    p.wait()
    version = tuple(map(int, output.split("\n")[0].split()[-1].split(".")))
    return version

def getGcdaFiles(args):
    gcda_files = args.gcda_files
    if args.gcda_list:
        with open(args.gcda_list) as f:
            gcda_files = f.readlines()

    return gcda_files

def processGcdas(gcov, jobs, gcda_files):
    chunk_size = int(len(gcda_files) / args.jobs) + 1

    processes = []
    for chunk in chunks(gcda_files, chunk_size):
        processes.append(subprocess.Popen([gcov, "-i"] + chunk, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL))

    for p in processes:
        p.wait()

def main(args):
    # Need at least gcov 7.1.0 because of bug not allowing -i in conjunction with multiple files
    # See: https://github.com/gcc-mirror/gcc/commit/41da7513d5aaaff3a5651b40edeccc1e32ea785a
    current_gcov_version = getGcovVersion(args.gcov)
    if current_gcov_version < MINIMUM_GCOV:
        print("Minimum gcov version {} required, found {}".format(".".join(map(str, MINIMUM_GCOV)), ".".join(map(str, current_gcov_version))))
        exit(1)

    gcda_files = getGcdaFiles(args)
    processGcdas(args.gcov, args.jobs, gcda_files)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Program description here')
    parser.add_argument('gcda_files', nargs='*', help='Optional positional argument')
    parser.add_argument('-g', '--gcov', dest='gcov', default='gcov', help='which gcov binary to use')
    parser.add_argument('-f', '--gcda-list', dest='gcda_list', help='Read list of gcdas to process from specified file (1 gcda path per line)')
    parser.add_argument('-j', '--jobs', dest='jobs', type=int, default=4*multiprocessing.cpu_count(), help='Number of parallel gcov to spawn (default: 4 * cpu_count)')
    args = parser.parse_args()
    main(args)
```

**Comment by latk** [comment]
Thank you @RPGillespie6 for that, this is enlightening. Unfortunately I think you'll have to keep using your fastcov tool  for now (or the similar grcov) as integrating these ideas into gcovr is a bit challenging and will take a lot of time.

1. This optimization can apparently only be chosen for gcov > 7.1. This requires that the test suite is first ported to more GCC versions than our baseline GCC 5 (cf #206). This might also affect llvm-cov compatibility.
2. This optimization requires that we know in advance which directory to invoke gcov from. This requires us to first design and implement user-controllable heuristics as discussed above.
3. The gcov generation must be lifted to operate on batches of gcda files rather than single files. This is probably the easiest part.

Note that your use of `gcov -i` (intermediate format) implies fundamentally different assumptions than gcovr:

 - Gcovr needs to process the source code in order to apply exclusion markers. Therefore, gcovr uses the human-readable gcov reports.
 - In order to create these reports, gcov must be able to locate the source code. Gcov must therefore be invoked in the correct directory.
 - The human-readable reports are named after the source files, not the object files. To avoid overwriting reports, only one gcov process may run in a directory at a time.
 - Furthermore, gcov's intermediate format has been replaced in GCC 9.x in favour of a new JSON-based format.

If gcovr is to follow a similar route (which I do plan to eventually do), gcovr will have to start locating and parsing the source files by itself.

I'm reopening this issue as there has been discussion of many ideas that should be revisited in the future.

**Comment by RPGillespie6** [comment]
> Unfortunately I think you'll have to keep using your fastcov tool for now (or the similar grcov) as integrating these ideas into gcovr is a bit challenging and will take a lot of time.

No worries. I enjoy tool development. fastcov will be MIT licensed, so feel free to steal any code you find there that may be helpful.

> This optimization can apparently only be chosen for gcov > 7.1

Only if using `-i` which I plan on using. Previous versions of gcov have multi-file support. GCC 9 will have an even better intermediate format (JSON) that can be consumed via stdout for even more speed gains.

> This optimization requires that we know in advance which directory to invoke gcov from. This requires us to first design and implement user-controllable heuristics as discussed above.

Another potential avenue could could explore is sorting gcda list first and chunking by directory. It's probably a safe bet that multiple gcdas in the same directory were generated from the same compiler location.

> Gcovr needs to process the source code in order to apply exclusion markers. Therefore, gcovr uses the human-readable gcov reports.

For fastcov I'm thinking of fundamentally moving away from the idea of generating the front end. fastcov will only ever generate intermediate formats and you can use either a frontend generator like genhtml or a dedicated web app to consume intermediate formats. 

For example, a simple MVC webapp using Vue or React could easily read in intermediate JSON, render high level report, and lazy load source files, using JavaScript to do everything from sorting, to line coloration, to skipping over exclusion markers. That way the coverage tool only ever needs to deal in intermediate formats and can be as lean and fast as possible.

> To avoid overwriting reports, only one gcov process may run in a directory at a time.

Could you expound on this a bit? I though gcov used `flock` to ensure nothing ever got overwritten in gdca and gcov files by competing processes?

**Comment by RPGillespie6** [comment]
I'll have to run a few experiments, but it seems like this can be solved using GCC 9's `-it` flags which would stream JSON intermediate format straight to stdout. At any rate, I'm not *too* worried about this since it only affects header files which (usually) don't have code in them. I could see how it might be a problem for .hpp header-only libraries, so I'll have to think about how to handle those, but there might be a way for the user to indicate how to resolve the race.

**Comment by RPGillespie6** [comment]
We can close this issue, BTW. It will be very difficult to speed up gcovr pre-GCC9.
