### ISSUE TITLE
Feature request: option to disable branch coverage

### ISSUE THREAD

**Issue by tovrstra** [gcovr/gcovr#303]
As explained in the following commit, branch coverage is never going to be perfect for C++: https://github.com/gcovr/gcovr/commit/84e85f0faa48c66bc01f6e79950a48cdab322a8f It would be convenient to have an option to disable branch analysis, essentially not passing the options `--branch-counts` and `--branch-probabilities` to `gcov` here: https://github.com/gcovr/gcovr/blob/master/gcovr/gcov.py#L636.

My motivation for opening this issue is that inherent limitations with branch analysis for C++ code result in unhelpful coverage percentages on codecov.io. The following is an example with 100% line coverage but showing up as 18.29% due to spurious missed branches: 

https://codecov.io/gh/theochem/cellcutoff/src/master/cellcutoff/tests/test_iterators.cpp

One could argue that codecov.io is processing the branch coverage incorrectly, but I guess that is always going to be debatable.

(I may be missing other ways to get around this issue. so feel free to fill me in.)

**Comment by latk** [comment]
Thank you for your report! I understand your frustration but don't think this can be fixed here.

I'm not sure how Codecov.io and gcovr are connected since gcovr does not produce an explicitly Codecov.io-oriented output format. If they were to be relying on gcovr's `-k`/`--keep` option to get access to the raw .gcov files, those reports will be incorrect anyway (coverage errors may be visible in header files that were compiled into multiple object files, since only one .gcov file can exist per source file). I took a peek at your project's travis.yml file but couldn't see how you're using gcovr.

Gcovr itself keeps statement coverage and branch coverage clearly separate, and the corresponding HTML report would show all those lines as “green“. Gcovr will try to strip exception-only branches from the reports if the `--exclude-throw-branches` option is provided (requires that you install the development version directly from GitHub).

So I am going to turn down this feature request:

* gcovr is a coverage report generator, not a gcov runner
* collecting different kinds of coverage data would complicate the internals substantially
* how Codecov.io renders their reports is a downstream problem, I have no influence on that

While I won't change how gcov is invoked, I am open to adding options to output formats. If you can figure out what format downstream tools would need, I can help you make the necessary changes to gcovr.

**Comment by tovrstra** [comment]
Thanks for the detailed reply.

I was using the XML output but I will check whether I can get better results by letting codecov.io parse the gcov files. (I recall that was also not ideal but I forgot the details. I'll post it below as soon as I recall.)

I just noticed that `gcovr` has the `-g` option, which would allow me to run `gcov` a priori with any option of interest.

**Comment by latk** [comment]
No, as mentioned above using the raw .gcov reports has grave problems: you will be unable to get accurate coverage for header files. And when running gcov a priori, the difficult part is to figure out where to run it. It should be run from the same directory as the compiler for the object file. This either requires knowledge about the build system, or a set of heuristics like gcovr uses.

Here, the better approach might be to strip branch coverage data from the Cobertura XML report.

**Comment by tovrstra** [comment]
Thanks. I'm somewhat new to this. I'll try your suggestions.

**Comment by tovrstra** [comment]
The ` --exclude-throw-branches` does indeed improve the situation, but still some spurious missed branches appear as expected, e.g. related to gtest. I did not try to manually filter out branch data from the xml file as it seemed too cumbersome.

The following experiment lead to rather useful results, so I'm just mentioning it here in case anyone is interested. (I'm not claiming it is a general solution, but works for me.) One can use similar tricks to the codecov Pypi script (see https://pypi.org/project/codecov/) to generate all `*.gcov` files. The following worked particularly well for my case, but may need to be adapted to the build system, e.g. to exclude certain files. (I am working in a conda env, so I need to provide the gcov binary.)

```bash
# Generate all *.gcov files, also for headers, mind the options.
find . -type f -name '*.gcno' -exec x86_64-conda_cos6-linux-gnu-gcov -pbc {} +

# Print a nice report with line coverage to stdout with gcovr.
# (running gcov is disabled, *.gcov files are kept)
gcovr -gk; 

# Upload *.gcov files to codecov. (running gcov is disabled)
CODECOV_TOKEN="..." codecov -X gcov
```

When visualizing this on codecov.io, it seems that their web app is capable of filtering out more (all?) spurious missed branches, only showing the ones that really matter.

**Comment by blueyed** [comment]
@tovrstra 
I would assume not running gcov manually should be better (less missed branches!), no?

Also, have you tried uploading an xml file?  (`gcovr -o coverage.xml --xml`, then `codecov -f coverage.xml`)
I've only quickly tested it with awesomeWM (https://github.com/awesomeWM/awesome/pull/2795), and it appears to have improved reporting of only partially covered branches.
(I was running gcov previously already per gcda file, with output to a separate directory)
