### ISSUE TITLE
Improve programmatic access

### ISSUE THREAD

**Issue by bracco23** [gcovr/gcovr#311]
I'm working on using `gcovr` to parse output on our unit tests.

Since invocation of `gcovr` from the command line is slow, I opted to import all the relevant processing data from a custom script which basically execute tests, collects `gcda` files and invokes `gcov` on them in the right folder,  uses `gcovr` parsing functionalities to print html and xml outputs.

What I noticed is that the different functions rely heavily on the options passed to the main script, so much that I had to recreate the object and customize.

It would be much better to not use the command line options in any module different than the main one so that other modules can use them without having to rely on the same object.

For example, `print_html_report` takes `covdata` and `options` as input. It is cleaner to pass the flags as separate parameters or as a custom `HTMLOptions` object, so that it can be used by other scripts in a much simpler way.

**Comment by latk** [comment]
@chenlijun99 Correct, no API has been exposed. At this time, gcovr only supports interaction via its command line interface. But you can “extend” coverage processing by manipulating the JSON output format. For example, if you want to customize coverage exclusion processing, you could do:

```bash
# 1. collect coverage data
gcovr --json raw-coverage.json

# 2. modify the JSON file as needed
./your-custom-filter <raw-coverage.json >processed-coverage.json

# 3. use gcovr to output a coverage report
gcovr -a processed-coverage.json --html-details report.html
```

At the time when this issue was closed, GitHub did not distinguish between “close as completed” and “close as not planned”. [That feature was introduced two months later](https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/).

**Comment by chenlijun99** [comment]
@latk Thanks for the suggestion! Thanks also for the GitHub history lesson :smile: !

**Comment by Spacetown** [comment]
Good to know that we can now close as not planned.
