### ISSUE TITLE
Replace custom logger with python logging module

### ISSUE THREAD

**Issue by bracco23** [gcovr/gcovr#312]
It would be easier and simplify integration with other modules to use the standard python `logging` package instead of relying on the custom solution.

This way it would be also easier to add different log levels and redirecting of logs to file instead of stdout.

**Comment by latk** [comment]
I agree. Gcovr is not using `logging` because it seemed like overkill at the time … and TBH I could never quite figure it out. I'm open to improvements, but please explain first what you'd be doing specifically and what benefits this will bring. If all that would have to be changed is the internals of the Logger class, that would seem like a win.

**Comment by bracco23** [comment]
As I explained in the other issue ( #311 ) I am invoking the parsing parts from another script.

My main problem with logging was that I was trying to redirect output to file instead of to stdout, which, because of the custom `Logger` object (instantiated multiple times inside the different functions) and of the hardwired output to `stdout` ( or `stderr` ) in it, I was having trouble. I tried replacing them but multithreading was getting in my way.

We could just replace the current `Logger` with a version as such:

```
import logging

class Logger(object):
    def __init__(self, verbose):
        pass

    def warn(self, pattern, *args, **kwargs):
        """Write a formatted warning to STDERR.
        pattern: a str.format pattern
        args, kwargs: str.format arguments
        """
        logging.warning(pattern.format(*args, **kwargs))

    def error(self, pattern, *args, **kwargs):
        """Write a formatted error to STDERR.
        pattern: a str.format pattern
        args, kwargs: str.format parameters
        """
        logging.error(pattern.format(*args, **kwargs))

    def msg(self, pattern, *args, **kwargs):
        """Write a formatted message to STDOUT.
        pattern: a str.format pattern
        args, kwargs: str.format arguments
        """
        logging.debug(pattern.format(*args, **kwargs))

    def verbose_msg(self, pattern, *args, **kwargs):
        """Write a formatted message to STDOUT if in verbose mode.
        see: self.msg()
        """
        self.msg(pattern, *args, **kwargs)

```
but I think removing the `Logger` class totally would be advisable, replacing with the calls to the corresponding methods directly.

To keep actual functionalities, `__main__.py` would set configs like this
```
if options.verbose:
    logging.basicConfig(level=logging.INFO)
else:
    logging.basicConfig(level=logging.WARN)
```

This would also give the benefit of handling without problems multithreading, easily allow to add options to `__main__.py` to redirect log to file and to give finer control of log outputs and to automatically inherit configs if invoke through another script instead of through command line. I don't know `logging` really good, but it also has functionalities related to named loggers which could turn out useful.

**Comment by latk** [comment]
Hmm, I'm not yet entirely convinced. Right now gcovr is an application and not a library, so redirectability is not an immediate concern for me. Although called `Logger` the class actually describes any kind of user-visible console output that isn't a report or a help message: for an unixly application, some kind of messages MUST be shown on stdout, but warnings MUST go to stderr.

If – one day, perhaps – gcovr exposes an API, then event-based output might be preferable since it allows logging for external users and user-friendly output for the main application. For example, the code currently says

``` python
logger.verbose_msg("Pool started with {} threads", pool.size())
```

which could be changed to

```python
ui.event_pool_started(pool.size())
```

For your immediate problem, it might be better to move any `Logger()` instantiations out of the gcovr.gcov module so that you can inject your own `Logger` implementation.

**Comment by bracco23** [comment]
While not exactly sure of what do you refer to with "unixly" applications, if the whole package is seen as an application `logging` doesn't indeed seem the right choice, at least for now.

Yes, refactoring `Logger` creation so that it is easily replaceable would make the code more easily to refactor in the future, maybe and it would indeed allow me to easier, but that is not that much important I guess.
