### ISSUE TITLE
Correct gcov files are not getting genrated for executable.

### ISSUE THREAD

**Issue by the-code-cult** [gcovr/gcovr#318]

**Comment by the-code-cult** [comment]
I have an executable, which is a result of a Test.cpp and ActualSource.cpp.
Linked to Gtest,GMock libraries. Upon compilation, I get *.gcno files. Upon Binary execution on the QNX_X86_64 VMware image I get *.gcda files.

When I run GCOV command over the project for the list of source files present in the project, I get below log information.
File 'D:/Work/Blackhole/UT_Jenkins/dia-aap-diagnostic-manager/lib/core/src/dia_coreplugin_routines/dia_Routine.cpp'
No executable lines
Removing 'dia_Routine.cpp.gcov'


**Note:**  But individually when I run the binary in the eclipse in debugging mode, I can see the actual code coverage, it is running the many API, 100s of lines of code is covered.

Please  share ideas whats going wrong here?

**Comment by latk** [comment]
That is a gcov-level error that is not immediately caused by gcovr. Or does
it work when you generate that gcov report manually?

Maybe one of these links will help:
*
https://www.gcovr.com/en/master/faq.html#why-are-uncovered-files-not-reported
*
https://stackoverflow.com/questions/44793894/gcov-giving-error-no-executable-lines

**Comment by Spacetown** [comment]
For me this seems to be the same problem as https://github.com/gcovr/gcovr/issues/403#issuecomment-667522168.
