### ISSUE TITLE
Addition of json reports 

### ISSUE THREAD

**Issue by Minkush-sopho** [gcovr/gcovr#321]
Addition of choice of json reports can be implemented which should just simply generate a json with missing lines coverage along with file name in a json format. 
Somewhat like this: 
`{
files: [
path: 'A.cpp'
coverage: {
line: 43
exec_count : 0
}
...
]
}`
Such form of report can be highly useful in integrating the coverage data in other development tools such Gerrit.

**Comment by latk** [comment]
Absolutely! Upstream gcov recently added JSON support (in GCC 9.1), and it would be great for gcovr to read/write this format as well. The upstream changes have been discussed in #282, a JSON-summary variant has been proposed in #301/#302.

I'd love it if you or anyone else would like to contribute full JSON support! But since this has already been raised in those other issues, I'll close this one here.
