### ISSUE TITLE
Generating coverage report on another machine?

### ISSUE THREAD

**Issue by inorton** [gcovr/gcovr#322]
My builds are executed inside docker containers, I have disposable build environments and only keep the build outputs (I keep my programs and the gcno files)

When I run my tests on a real system I see gcda files being created correctly, I can change where they appear by setting GCOV_PREFIX and GCOV_PREFIX_STRIP and this works.

However, gcovr reads the original compile-time absolute path from the gcda files (which is not on this test machine) yet I do have the source tree availble (just at a different absolute path).

The error messages appear as warnings like so:
```
(WARNING) GCOV produced the following errors processing /home/devel/bamboo-agent-home/xml-data/build-dir/CIR-CKCOV-CKL64/build-host-linux-gcov/cutils/examples/CMakeFiles/examples-obj.dir/ncthread-unix.c.gcda:
		Cannot open source file /home/devel/bamboo-agent-home/xml-data/build-dir/NC-MAIN01-GCOV64/cutils/examples/ncthread-unix.c
```

How do I tell gcovr to actually look in my `--root` folder instead of these absolute paths in the gcda files?

**Comment by latk** [comment]
Hmm, in general you can only run gcov/gcovr on the same system where you compiled the program to be covered. In this case, that would be the container. My preferred solution would be that you perhaps create a container with the required directory structure, and run gcovr in there.

The immediate error that you are seeing is that gcov – not gcovr – cannot find the source file. I am not sure how or even if gcov can be told to look elsewhere. Unfortunately gcovr can currently only use the gcov mode where it creates an annotated source report, therefore any such path transformations would have to happen on the gcov level first. This would change when support for the gcov json format is implemented (#282). Another alternative would be to make gcc put relative paths into the object and coverage files, but I doubt this is possible.

I'm going to close this issue because this is a niche case that cannot be reasonably supported. Still, thank you very much for raising this issue, as it would be an interesting capability in the future – especially considering that such container-based builds will only become more common.
