### ISSUE TITLE
exclude-unreachable-branches: ignore false branches with "assert" statements

### ISSUE THREAD

**Issue by blueyed** [gcovr/gcovr#324]
I wonder if it would make sense to give special treatments to `assert` statement.

E.g. with `assert(sig == SIGTERM || sig == SIGKILL);` it might show:

- Branch 0 not taken
- Branch 1 taken 2 times
- Branch 2 not taken
- Branch 3 not taken

While here it is a good indication that only `SIGTERM` is used, it should not really cause missing branch coverage likely for Branch 0 and 2 at least.

It is more obvious with `assert(sig != 42);`:
- Branch 0 not taken
- Branch 1 taken 2 times

It makes more sense to report if some `assert` was not called/used in the first place though (no branch taken).

This could/should be handled with `--exclude-unreachable-branches` then maybe.

**Comment by latk** [comment]
That's a great idea! But it is a bit tricky:

* [The branches are real](https://gcovr.com/en/master/faq.html#why-does-c-code-have-so-many-uncovered-branches) so it does make sense to show them.
* But these branches are not generally interesting for test coverage.

Gcovr has three mechanisms to deal with unwanted coverage data:

* `--exclude-unreachable-branches` ignores branch coverage on lines that do not seem to contain code. E.g. GCC attributes static initialization to the last code line in a file, which usually contains a closing curly brace.

* `--exclude-throw-branches` ignores branches that GCC marks as exception only. This is mostly relevant in C++. Use of this feature is a double-edged sword. Often you're not interested in covering the branch from a function that throws, except when you have an explicit `catch` block.

* [Exclusion markers](https://gcovr.com/en/master/guide.html#exclusion-markers) such as `GCOVR_EXCL_LINE` ignore coverage from specific lines.

What gcovr does not attempt to do is to parse or understand the source code. It is therefore limited by simple heuristics and by the data that GCC/gcov make available. I *will not* add a rule that ignores branch coverage on any line that matches a regex like `/^\s*assert\(/`, that seems too error-prone.

However, **I am open to improvements to the exclusion marker mechanism.** Currently, exclusion is handled directly during gcov file parsing, which is inflexible. A better design might:

* move exclusion marker processing to a post-processing phase between coverage collection and report rendering
* or perhaps move exclusion markers directly into the data model?
* make the exclusion markers configurable per the config file

Such an improved approach would also allow exclusion of branch coverage, rather than all coverage on the line. A project could then configure gcovr to ignore branches on the asserts that they use, which won't necessarily be the C standard library `assert()` macro. Lcov supports precisely such a feature.

If you or anyone else would like to work on this, please discuss a proposed design on this issue before working on a pull request.

**Comment by ThomasFeher** [comment]
I've stumbled upon this lately, too. For me a sufficient solution would be to implement https://github.com/gcovr/gcovr/issues/121 so one can manually mark asserts to be excluded from branch coverage.

**Comment by tamasseller** [comment]
+1 on the post-processing idea, it seems to be very cumbersome to annotate every assert line with the exclusion marker, but not being able to filter out those skews the branch coverage summary so much that it is almost not useful at all. The same goes for generated null checks in delete operator invocations. The post-processing step could also be though of as generalization of the current markers because those can still be implemented using a default script.

**Comment by KantarBruceAdams** [comment]
I raised this issue on the sonar forum [here](https://community.sonarsource.com/t/disable-branch-coverage-for-assertions/59974). I don't know if its the official stance but it was suggested this is a job for the coverage tool.

I just noticed the --exclude-lines-by-pattern feature. Surely this is perfect for this case?
It presumably removes both line and branch coverage but line coverage for an assertion is not very helpful either.

I can see uses for exclusion markers but it makes me uncomfortable. You could have to annotate far too much code. A tool like this should be less intrusive.
Even so I feel I should mention the new attributes in C++20 [likely](https://en.cppreference.com/w/cpp/language/attributes/likely) & [unlikely](https://en.cppreference.com/w/cpp/language/attributes/likely) as these or something like them could perhaps be automatically interpreted as 'exclude branch coverage' if only they could be extracted without a parser.

Excluding entire files matching a pattern (for example as per https://github.com/gcovr/gcovr/issues/482 ) is useful but not fine grained enough.

Similarly ignoring all exceptional branches seems too heavy handed. There must be many that are worth testing and therefore which are worth measuring coverage for.

What might a post processing approach look like? 
What is gcovr's data model?

I guess it is based on what can be parsed from the .gcov files?
It should not be based on line numbers or anything else prone to change when unrelated code changes.
It is hard to see what else could be used without pulling in an AST from the compiler or some other parser.

**Comment by KantarBruceAdams** [comment]
--exclude-lines-by-pattern '.*assert.*' handles this case nicely for me.

**Comment by Spacetown** [comment]
I close this since there is an option to ignore the line by a RegEx and code comments to ignore the line or the branches in the line.
