### ISSUE TITLE
Reading coverage after EOF

### ISSUE THREAD

**Issue by HannesFranke-smartoptics** [gcovr/gcovr#330]
Hello, I am using clang-7s `llvm-cov gcov` for coverage generation but that seemn to generate entries after EOF of the file which are not correctly ignored.

```
$ llvm-cov --version
LLVM (http://llvm.org/): LLVM version 7.1.0
$ gcovr --version
gcovr 4.1
```

The report contains
```
<class [...] filename="test.cpp" [...]>
    <line branch="false" hits="0" number="523"/>
    <line branch="false" hits="0" number="524"/>
```
But the file only has 461 lines.  
Generating the intermediate output (command taken from `gcov -v`)
```
llvm-cov gcov test.cpp.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory [build_path]
```
And inspecting  the `.gcov` file shows
```
branch  0 never executed
branch  1 never executed
        -:  453:                    }
        -:  454:                }
    #####:  455:            }
    #####:  456:        }
        -:  457:        else
    #####:  458:            continue;
        -:  459:    }
    #####:  460:}
        -:  461:/*EOF*/
        -:  462:/*EOF*/
        -:  463:/*EOF*/
[SNIP: repeat for 464 to 520]
        -:  521:/*EOF*/
        -:  522:/*EOF*/
    #####:  523:/*EOF*/
    #####:  524:/*EOF*/
```

and the offending lines are exactly 523 and 524. I don't know weather its `llvm-cov gcov` or `gcovr` which is misbehaving in this instance.

**Comment by latk** [comment]
Uuh, that doesn't look good. But thank you for already including information for debugging!

What can happen is that the tools get confused about the source file, especially if you have multiple source files with the same name. There could also be problems if the gcda/gcno files were not created on the same computer, or if they were created by a different compiler. Could you please check if any of those scenarios applies?

Since you can reproduce the problem with llvm-cov itself, without using gcovr, the problem doesn't seem to be with gcovr itself. I'm not sure if there is anything I can do to fix the problem aside from general tips.

For what it's worth I tried running a simple test case with the llvm 6.0 I have installed, but I didn't get EOF in the gcov reports.

**Comment by HannesFranke-smartoptics** [comment]
> What can happen is that the tools get confused about the source file, especially if you have multiple source files with the same name. There could also be problems if the gcda/gcno files were not created on the same computer, or if they were created by a different compiler. Could you please check if any of those scenarios applies?

This is the only source file with that name (although some included files might have the same name but different directories). Everything was executed on the same machine and without any compiler/tool changes inbetween. I'll probably file a bug against llvm then.

**Comment by latk** [comment]
If you can create a reproducible example with an up to date LLVM version, then filing an upstream bug might indeed be sensible.

However, I'm not yet convinced that it is an upstream bug. Do you see the expected source code in the gcov file?

Either way, reducing this to a small example would help investigate the problem.
