### ISSUE TITLE
GCOVR seems to have a branch counting problem

### ISSUE THREAD

**Issue by iuripereira** [gcovr/gcovr#339]
I have a piece of code zipped to explain my question

I compiled it with GCC 8+ with the command:
`g++ -O0 --coverage -fno-exceptions -fno-inline main.cpp -o main`

After that I executed the following command:
`gcovr -r . --html -o index.html -p --print-summary --html-details  --exclude-unreachable-branches --exclude-throw-branches
`

When I was seeing the report, it shows me 1 of 2 branches taken at line **delete m** . Wich for me it was kinda awkward. 

Then I git cloned LCOV 1.14 and tried to make the same thing and with lcov this behavior is not present. There's no branches is this code.

Do you think there is a bug counting branches in gcorv or am I wrong?
[main.zip](https://github.com/gcovr/gcovr/files/3861276/main.zip)

**Comment by latk** [comment]
I'm not an expert on lcov, but I can explain why gcovr shows missing branch coverage there. As I understand it, gcovr's behaviour is correct in this case.

Gcov-based branch coverage data (as used by lcov, gcovr) is based on assembly-level control flow, and not just control flow constructs in your actual language (like C++). That means that if the compiler inserts branches, gcovr will see them as well.

The [`delete expr` operator in C++](https://en.cppreference.com/w/cpp/language/delete) has two operating modes:

* if the `expr` is a null pointer, no destructor is called and a deallocation function *may* be called
* if the `expr` is a non-null pointer, the destructor and a deallocation function is called

GCC internally deals with two kind of destructors: normal destructors and deleting destructors, so that no deallocation function will be called directly here. However, GCC still needs to include a branch to check for a null pointer. Effectively:

``` c++
if (m) {
  m->~MyInterface();  // deleting destructor
}
```

You can inspect the actual assembly here: https://godbolt.org/z/Zm7SWp (I stripped away the --coverage option because it just inserts hard-to-read junk).

This branch is real, and therefore included in the coverage data. It is not an exception branch. It is not feasible for gcovr to specially detect and remove this case.

Of course, this branch is unreachable, which is why GCC will remove it with `-O1`. Choosing the appropriate optimization level for coverage collection is tricky: a too low level might let the compiler insert unnecessary branches, but a too high level might remove branches you are interested in.

My tip is to ignore branch coverage data as a summary metric, and only consider it when manually looking at the code, e.g. for coverage-guided testing.
