### ISSUE TITLE
hilite unexecuted executable lines

### ISSUE THREAD

**Issue by StevanWhite** [gcovr/gcovr#343]
In its HTML output, gcovr hilites lines that are executed, and is concerned with how many times they were executed.  This is great for understanding performance.

Another important function of coverage is to check that all code has been tested, that is, to clearly indicate any code that has *not* been executed in the tests.

But (near as I can tell) the HTML output of gcovr doesn't distinguish between non-executable lines (comments, declarations, and blank lines) and executable lines.  This makes it very hard to perform this necessary coverage check.

It would be very helpful if all executable lines were somehow marked.  For instance, by hiliting them in light gray, it would be visually obvious that some lines had been overlooked in tests.

**Comment by latk** [comment]
Thank you for this suggestion! Gcovr marks uncovered lines with a red background, but has no way to detect code that “doesn't exist”.

Gcovr depends on GCC to instrument the generated machine code with counters. This means that gcovr “sees” all the actual branches and blocks in the executable, but it also means that it doesn't see stuff that the compiler optimized away. In particular, **the compiler will not generate machine code for inline functions or templates if they are not used.** As far as GCC/gcovr is concerned, such code does not exist.

A related Gcovr FAQ entry about the opposite problem: [Why does C++ code have so many uncovered branches?](https://gcovr.com/en/stable/faq.html#why-does-c-code-have-so-many-uncovered-branches)

This is a fundamental limitation of the way coverage data is collected. I will not add a source code parser to detect lines of code that look like they might be uncovered, especially since this would be rather faulty in complicated settings (e.g. code that is excluded via an ifdef). However, future versions of GCC could make more data about uncovered lines available.

My recommendation is to manually review the coverage of source files to ensure that all functions were actually instantiated, or to look at coverage tools that actually parse the source code to calculate coverage.

**Comment by StevanWhite** [comment]
Thanks for your prompt reply!

My report was about what a developer expects from a coverage system.  
How it is implemented, is another question.

It seems to me that some means other than gcov could be used to distinguish lines that are in principle executable, and that gcovr could mark them accordingly.  I maintain that this would be useful for your project.

**Comment by latk** [comment]
I understand. Such a feature _would_ be very valuable! I had your exact problem myself many times. But given that the extreme software development effort such a feature would require, I don't expect gcovr to support this.

That said, if someone does know a reasonable way to parse GCC-supported languages (importantly: C++), then I'd be open to discussing optional support for such checks. Maybe Python's libclang bindings would allow this? However, I don't have time to do this myself, and can't encourage this either: even if there was a suitable parser, actually integrating and maintaining this feature would take nontrivial effort.
