### ISSUE TITLE
BUG: Please fix workers.py import queue 

### ISSUE THREAD

**Issue by Cherish-Gww** [gcovr/gcovr#354]
queue package in python2.7 and python 3.5 is different, please change workers.py as flows
```
try:
   from queue import Queue, Empty
except ImportError:
   from Queue import Queue, Empty
```

**Comment by latk** [comment]
Thank you for reporting your issue, but this is by design.

Please see the supported Python versions in the [installation documentation](https://github.com/gcovr/gcovr/blob/master/doc/source/installation.rst) ([website](https://gcovr.com/en/master/installation.html)). With the next release, support for Python 2.7 will be dropped, and only 3.5+ is supported. So the release gcovr 4.2 is the last version to support Python 2.7. This was announced prominently in the [4.2 changelog](https://gcovr.com/en/4.2/changelog.html).

Gcovr's master branch is the development version, and Python 2.7-support had already been removed back in December: https://github.com/gcovr/gcovr/commit/92b88996fc1677755be92fdbd7f902f578e2ba35#diff-5cc0ebdd5dc443345645d0a5045e5ea9

**Comment by Cherish-Gww** [comment]
@latk  Thank you.
