### ISSUE TITLE
After updating from 4.1 to 4.2, gcovr fails to generate files as before update

### ISSUE THREAD

**Issue by Verequus** [gcovr/gcovr#364]
I've been trying to update the gcovr module from 4.1 (which works fine) to 4.2, but that doesn't work correctly. The setup is basically like this: For every module we want to run gcovr the folder structure is like:

```
<module>
+src
+test/UT
```

Inside UT the makefile is called both to compile the files as well to execute the tests. gcovr is called from this directory with this:

```
"py -m gcovr --object-directory=../../{0} -r . --html --html-details -o coverage.html --html-title \"Coverage Report for {1}\" --print-summary".format(source_dir, module_name)
"py -m gcovr --object-directory=../../{0} -r . --xml --xml-pretty -o coverage.xml".format(source_dir)

```
where source_dir = "src" and "module_name" is the name of the module.

Since 4.2 changed the meaning of "--html" and "--xml", the call like this fails already. So I reordered the calls to this:

```
"py -m gcovr --object-directory=../../{0} -r ../../{0} --html-details -o coverage.html --html-title \"Coverage Report for {1}\" --print-summary --html".format(source_dir, module_name)
"py -m gcovr --object-directory=../../{0} -r ../../{0} --xml-pretty -o coverage.xml --xml".format(source_dir)

```

This ends up with an empty coverage.html, where instead the directory reference from "../../src" is "." instead and the source file to be analyzed neither longer appears in the main file nor as its own file (see in
[coverage.zip](https://github.com/gcovr/gcovr/files/4511312/coverage.zip) each html file respectively - the xml files are similar).

If I try to use the "--html" and "--xml" parameters by adding "coverage.html"/"coverage.xml", the result does not change, only a warning about ignoring "--output" appears.

What do I have to do to make this work again? Or is this actually a bug in gcovr 4.2?

**Comment by latk** [comment]
I am quite confused by this setup, both by how things used to work and how things subsequently broke.

* The `--object-directory` flag almost never does what you want, but is one way to provide a search path for the .gcda/.gcno files. But here you're pointing it to your src directory?
* The `--html` and `--xml` flags were changed to take an *optional* argument. That was not strictly backwards-compatible. However, your original commands are not ambiguous? How did things fail after the update?
* `-r ../` style invocations are only fixed/supported since recently, so there could be bugs. This parameter does many things, but mostly it's just a default filter. I'm therefore not sure how things could have worked previously, as `.` would be `test/UT` and only contain the tests but not the code you're trying to cover?

Please provide the following information so that I can understand this setup:

* given source files like `src/code.c` and `test/UT/test.c`, where do the object files end up?
* Are they all compiled by `test/UT/Makefile`? Or is there a separate Makefile for src?
* In those Makefiles, how is GCC invoked? From the same directory, or is a `cd` involved?
* You are running gcovr with `test/UT` as the current working directory, right?

It would also be helpful if you can run gcovr in --verbose mode, as that provides lots of info about which .gcda files are found and which source files are excluded by some filter.

**Comment by Verequus** [comment]
Sorry for the delay, work was very busy.

To dispel your confusions:

* `--object-directory` points to src, because the .gcda/.gcno files for the source files are in there (yes, we still have no separate folders).
* `--html` and `--xml` are indeed innocent, I thought initially it was the cause and never noticed that the issue persisted regardless of order of parameters. So I'll keep the order of parameters as it is.
* I did try to change `-r .` to `-r ../../src` but that failed to provide the correct paths (can't quite remember now what the issue was now). So if the call worked for gcovr 4.1 by chance, I don't know why it would fail now.

The other four points:

* The object files are in the same directory as their respective source file (`src` and `test/UT`).
* Both `src` and `test/UT` are compiled by the same `test/UT/Makefile`.
* I'll paste the relevant part of the makefile below:

`MAKE=mingw32-make

TARGET=UT_<modulename>
SRC_UT=$(wildcard *.cpp)
SRC_MODULE=$(wildcard ../../src/*.c) 
OBJ=$(SRC_UT:.cpp=.o) $(SRC_MODULE:.c=.o)

%.o: %.cpp
	$(CXX) -c -o $@ $< $(CXXFLAGS)

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS)

$(TARGET): $(OBJ)
	$(MAKE) -C <various Mocks (not included in coverage)>
	$(CXX) -o $@ $^ $(LDFLAGS)

run: $(TARGET)
	$(TARGET).exe --gtest_output=xml:testresults.xml
`
* Yes, `test/UT` is the current work directory from where make is started.

I have also created [log-4.1.txt](https://github.com/gcovr/gcovr/files/4547140/log-4.1.txt) and 
[log-4.2.txt](https://github.com/gcovr/gcovr/files/4547141/log-4.2.txt). They have redacted to protect the innocent, but the essential parts have been left.

**Comment by Verequus** [comment]
Friendly reminder to look into this. :)

**Comment by Spacetown** [comment]
It's difficult to reprocuce without a complete examle. I've tested a little bit with the informations.
The test:
```
all:
	&& $(CXX) -fprofile-arcs -ftest-coverage -fPIC ../../src/main.cpp -o testcase

xml:
	.testcase
	$(GCOVR) --object-directory ../../src -r ../../src --verbose --keep --xml --xml-pretty -o ../../coverage.xml
```
gives an empty XML file. This is because the coverage files are generated in the `test/UT` directory and searched by default only in `--root` and `--object-directory`.

Removing `--object-directory ../../src` and adding an positional argument `.` as search path for gcov files will result in an on empty output file.

Changing to:
```
all:
	cd ../../src&& $(CXX) -fprofile-arcs -ftest-coverage -fPIC main.cpp -o testcase

xml:
	./../../src/testcase
	$(GCOVR) -r ../.. --verbose --keep --xml --xml-pretty -o ../../coverage.xml
```
gives a file with data.

**Comment by Spacetown** [comment]
@Verequus Can you test this with the current master branch? For me it looks like the problem solved with #410.

**Comment by Verequus** [comment]
@Spacetown The build environment is depending on a wheel release package like provided on PyPi. How do I create one? Or can you attach one for me?

**Comment by Spacetown** [comment]
@Verequus I had to look for it first this because I've never done this before.
Clone the current master and run following command in the root directory of the clone:
```
python setup.py bdist_wheel
```
This will create the wheel file in the `dist`directory.

**Comment by Verequus** [comment]
I've tried now to create this distro, but setup.py doesn't seem to support bdist_wheel as parameter. There are a number of other options related to bdist, but none seem to be relevant.

**Comment by Spacetown** [comment]
Can you post the error message? I've tried the command on MacOs and the wheel file was generated.

**Comment by Verequus** [comment]
> $ python setup.py bdist_wheel
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
> 
> error: invalid command 'bdist_wheel'

The "python setup.py --help-commands" results in [help.txt](https://github.com/gcovr/gcovr/files/5193622/help.txt). I run Win 10 with Python 3.6.8, if that matters.

**Comment by Spacetown** [comment]
As I mentioned, I'm using a Mac. The wheel is a binary distribution depending on the OS and the used python.
It seems that you haven't installed the wheel package.
```
python -m pip install wheel
```

**Comment by Verequus** [comment]
Managed to get around doing that test, but no change to the results when running the UT job.

**Comment by Spacetown** [comment]
@Verequus Can you upload a smal make with sources to reproduce the error?

**Comment by Verequus** [comment]
So by chance a colleague of mine figured it out. We had to add a new parameter. From only (irrelevant other parameters redacted)

`--object-directory=../../{source_dir}`

to

`--object-directory=../../{source_dir} --filter ../../{source_dir}`

Leaving this for posterity.
