### ISSUE TITLE
The file name has underscore sign instead of dot in extension

### ISSUE THREAD

**Issue by Eldadc** [gcovr/gcovr#370]
Hi,

After created a cobertura report , It seems all file names have underscore sign instead of dot in the file extension. 

Example : abc_cpp
Is it by design? 

Thanks

**Comment by latk** [comment]
Yes, this is by design. Cobertura is a Java-centric format which is structured in terms of packages/classes. Java uses `.` as a package-separator, so we avoid names like `abc.cpp` in the class name field. In contrast, `abc_cpp` is a legal Java identifier. I'm not sure whether this is strictly necessary, but I wouldn't want to change it without very good reason. The XML includes the original filename in the `<class filename="...">` attribute.
