### ISSUE TITLE
Add color themes for html report

### ISSUE THREAD

**Issue by Spacetown** [gcovr/gcovr#381]
From work I know CTC which uses red/blue, Jenkins default is also red/blue because of redgreen blind people. It would be nice to have such a feature for gcovr also.

**Comment by latk** [comment]
Absolutely! Now that the HTML is mostly cleaned up, improving accessibility should be on the roadmap. I have mild color deficiency myself, and find gcovr's pinkish/magenta hue absolutely maddening.

Do you have a specific colour scheme in mind? Do you think we should change the default, or just implement a colour-blind mode?

In any case we should probably also add a textual indicator to uncovered lines, even if it's just a `-` hyphen.

**Comment by Spacetown** [comment]
I've no schema in mind but I would change the default to a red/blue schema using lightblue instead of lightgreen. In this case the table background (SteelBlue and LightSteelBlue) should also be adapted to distinguish between the coverage colors.
Or is it better to use stronger colors?

Textual indicators will be good. What about the symbols from https://github.com/gcovr/gcovr/issues/360#issue-590526820?
I'm not interested in a dark mode.

BTW: Is this realy a Bug?

**Comment by latk** [comment]
I've been experimenting a bit with colors, and think that more saturation than the current highlighting could be useful, at least if we want to keep the medium-gray left columns in the detail report. Here's a screenshot with red and blue hues, set to 60% saturation `#FF7D66` `#66D9FF`. Since the `&cross` symbol is no longer used for branch coverage, it could be repurposed for line coverage. 

![Screenshot_20200531_232604](https://user-images.githubusercontent.com/1782927/83363023-8d034100-a385-11ea-9c83-80c171edd160.png)

But perhaps it would be useful to have further contrast between covered and uncovered lines? If so, using something like `#99E6FF` to de-emphasize covered lines could be useful. Lightblue would be the same hue, just with even less saturation and a bit darker.

> BTW: Is this realy a Bug?

Accessibility problems are arguably a defect.

**Comment by Spacetown** [comment]
What about using the red from the Codecov running fot the PRs and use a blue with the same saturation?
Do we really need to change the background of the whole line?
CTC only change the foreground and the color of the meter in the overview and uses different colors in the details. https://verifysoft.com/en_ctcpp.html

**Comment by latk** [comment]
Good point, colors for bars and backgrounds can be different. CTC bars look good, but their line backgrounds have the same problems as current gcovr. Codecov backgrounds seem fine.

I'd ultimately prefer if you make the call on the specific colors because I don't trust my sense of style. As long as objective contrast criteria between text and background are fulfilled, and as long as uncovered things stand out, everything is going to be an improvement.
