### ISSUE TITLE
Errors when gcov path contains space

### ISSUE THREAD

**Issue by cconverse711** [gcovr/gcovr#384]
Should probably use `shlex.split` to properly handle spaces in quoted paths

https://github.com/gcovr/gcovr/blob/56e2b2e2af2d8bf01ff9c283b24433a07e32657d/gcovr/gcov.py#L629

**Comment by cconverse711** [comment]
Note that this is from running gcovr on Windows 10, with gcov installed from mingw-w64, at its standard filesystem location under "C:\Program Files"

**Comment by latk** [comment]
Good idea! This seems obvious in hindsight, and I'm sorry it's causing problems on Windows.

Looking at the [shlex documentation](https://docs.python.org/3/library/shlex.html) (especially the final sections *parsing rules* and *improved compatibility*), I have some design questions though. What are your thoughts?

* Should we use the Posix-compatible parsing mode?

  I think so, because anything else would be extra confusing (even though the Posix rules are confusing to start with, for people that don't know the Shell).

* What parsing mode should be used on Windows?

  Cmd\.exe has different quoting rules, but it might be sensible to use the same syntax on all platforms, in particular to support cross-platform build scripts and shared config files? However, Posix rules treat backslash `\` as an escape character, which might be inconvenient on Windows.

  I think that the benefit of using the same syntax on all platforms outweighs Windows inconveniences.

**Comment by cconverse711** [comment]
Thanks for the quick response! Yes, I agree that Posix parsing mode should be used even on Windows. I don't think I've ever had a reason to use non-Posix parsing mode.

**Comment by latk** [comment]
Ok, sounds good!

If you'd like to take a shot at fixing this issue and making a pull request, there's our contribution documentation here: https://gcovr.com/en/master/contributing.html#how-to-submit-a-pull-request

But I think that setting up a dev environment might be more difficult than making the actual fix! For this targetted change, it's probably OK to skip local testing and rely only on the CI.
