### ISSUE TITLE
Why Coverage does not hit the name of functions ?

### ISSUE THREAD

**Issue by Eldadc** [gcovr/gcovr#398]
Hi,

I am combining coverage results done by OpenCPPCoverage and GCC-Gcovr
I have noticed that on GCC built in coverage reports the name of the function is included in the hit counter
But OpenCPPCoverage doesn't include the line of the name of a function on the hit counter.
How can I adjust it with gcovr ?

Thanks
Eldad

**Comment by latk** [comment]
Could you show an example of what you mean? I'm not sure I understand correctly.

Gcovr doesn't currently report function coverage or per-function line/branch coverage:

* function coverage metrics are unreliable in any GCC/gcov based tool because `inline` functions that are never called "don't exist"

* per-function line/branch coverage metrics are available in gcov, but gcovr hasn't implemented the necessary code to extract and track these statistics. There are some differences between GCC versions that complicate this.

**Comment by Eldadc** [comment]
Thanks of the quick response.
Gcovr\GCC hit the name of the function in the coverage reports, the name of the coverage in the code has hit value.
Is it possible to control it.
When I merge gcovr results with coverage results with OPENcppCoverages tool, there is a mismatch because opencppcoverage doesn't include function name .

Thanks

**Comment by latk** [comment]
Ah, OK. I think I understand: your problem is that you have source that declares a function code like

``` c
1: int foo() {
2:  ...
3: }
```

and the gcovr report shows coverage data for the line `1` that only contains the function name. You want to ignore any coverage on this line.

I'm afraid that currently there is no option to detect or control this. Implementing this wouldn't be impossible, but it would require working on some of the more difficult parts on Gcovr.

Here's the part of gcovr that recognizes a function line in the gcovr report:

https://github.com/gcovr/gcovr/blob/b49ce8dd6aa00b825e312d602f31d08dd46b8c9f/gcovr/gcov.py#L355-L356

It would have to be changed to set a flag that causes coverage on the next line to be ignored, if the user requested this via some option.

I don't want to implement this myself. But if anyone else would like to take a shot at this, it might be a useful feature. If _you_ would like to try, you can find some tips to get started in our [contribution guide](https://gcovr.com/en/latest/contributing.html)

**Comment by Eldadc** [comment]
I understand. Thanks for the quick response.
Is there a workaround by editing results with a script ?
Thanks

**Comment by latk** [comment]
As a workaround you could try writing a regex that matches only function definitions in your source code, then exclude those lines. This would require you to install the development version of gcovr. I think something like this should work, depending on your coding style:

    gcovr ... --exclude-lines-by-pattern '^'\s*(?:static\s+)?[\w:*&\s]+\s+[\w:]+\([^\)]*\)\s*\{\s*$'

Explanation: match lines that

* `^\s*` optionally start the line with some space
* `(?:static\s+)?` optionally have the word "static"
* `[\w:*&\s]+` have a combination of words, spaces, and `:*&` to match a possible return type
* `\s+[\w:]+` match a (member) function name after a space
* `\([^\)]*\)` match function parameters which may be empty
* `\s*\{\s*$` end the line with an opening brace

Of course, this will break if the parameter list spans multiple lines, or for const-qualified member functions, or for trailing return types, or templates, or constexpr functions, or when function pointers are involved … this is really complicated, so gcovr doesn't attempt to do this by default.

If you have a different tool that can give you the line numbers for functions, a more robust approach would be possible: ask gcovr to generate JSON output, then process the JSON to delete coverage from unwanted lines, then use `gcovr -a coverage.json --xml output.xml` to generate the reports you need for further processing (Cobertura XML or any other format).

**Comment by Spacetown** [comment]
I've pushed a first approach. The property `gcovr/function` is added to the JSON. The value is True, if the line is following a fuction definition.
With the option `--exclude-fuction-coverage` the lines with a value of True are ommited and the coverage is changed because the branch isn't counted anymore.

**Comment by Spacetown** [comment]
@Eldadc Hy are you laughing?

**Comment by Eldadc** [comment]
Thanks so much on the effrots !
