### ISSUE TITLE
Generate also a Report of Excluded Coverage

### ISSUE THREAD

**Issue by kolrami** [gcovr/gcovr#409]
We support to exclude coverage from some regions via the GCOVR_EXCL_... markers. In my opinion these should only be used with care and if really necessary.  To judge the places where the markers are used it would be nice to include them in some way to the overall reports. I could imagine some ways (for e.g. the HTML report):

a) We have another column which shows how many lines are skipped. Then we can quickly judge how many lines are not considered?
b) We add an additional page which lists all places where we exclude coverage?
c) We mark the excluded regions with a special color in the detailed coverage report, currently they are just not marked at all.

**Comment by latk** [comment]
I see the point of this feature – kind of like marking the coverage as NaN instead of covered/uncovered. Collecting these statistics would not be overly difficult.

Off the cuff, your solution c) seems best. Adding a column takes up a lot of valuable space, and another page would involve more development effort. But adding a background in html-details might work.

What do other coverage tools do? Is there prior work that could serve as inspiration?

But what makes me slightly hesitant is that this adds another state that a line could have from a user's perspective:
clearly not code, contains code but was ignored by the compiler, uncovered lines, covered lines with partial branch coverage, fully covered lines.

**Comment by Spacetown** [comment]
In the HTML we have a green and a blue theme
To find a colour which is easy to distinguish even with a handycap is not easy. I would prefer a symbol like the cross for uncovered lines.

**Comment by latk** [comment]
I'm reopening this due to the problem found in https://github.com/gcovr/gcovr/pull/503#issuecomment-1214439044
