### ISSUE TITLE
 error: expected identifier before numeric constant in ceedling

### ISSUE THREAD

**Issue by padmavathitiwari** [gcovr/gcovr#411]
hi, 

i am trying to generate html report using gcov and gcovr.  getting following errors, can anyone help me on this ?

![image](https://user-images.githubusercontent.com/17330289/91305676-01088600-e7c9-11ea-9921-f2f6724c4a05.png)

**Comment by chrta** [comment]
These errors are issued from the compiler. It looks like your build environment is not working (since windows header are pulled in and also stm32 header). This is completely independent from gcovr. Maybe you can ask your question in some ceedling group/forum/list to get proper help setting up your build environment.
