### ISSUE TITLE
Multiple uncovered branches shown for an if-else

### ISSUE THREAD

**Issue by Diana-Lorena** [gcovr/gcovr#431]
When running gcov for my tests, there are multiple if-elses that appear to have multiple branches to cover (more than the normal if and else). For example:
void function(E const &event)
    {
        if (nullptr != object)
        {
            object->handleEvent(event);
        }
    }

For the above function the results look like the the ones from the attached picture. Even though I enter both if and else, it seems that there are multiple uncovered branches that lower my coverage. How can I get rid of that and why is it happening?
P.S: this is the only function in the file with branches, so for sure this is affecting the coverage.
Thanks
![coverage](https://user-images.githubusercontent.com/62993766/95449942-27941200-096e-11eb-8b4e-2e169ce3dd4c.png)

**Comment by latk** [comment]
Hello! This looks like lcov output, but this is the issue tracker for gcov**r**. But because both lcov and gcovr use GCC's gcov coverage data, we also get this question frequently.

We have a FAQ entry [Why does C++ code have so many uncovered branches?](https://gcovr.com/en/stable/faq.html#why-does-c-code-have-so-many-uncovered-branches) In a nutshell, GCC inserts extra branches around function calls for handling exceptions, destructors, and static initialization. These are real branches in the machine code, and are counted because gcov data is tracked on a machine code level, not on a source code level. I'm not sure how you can exclude these in lcov, but gcovr has two options to remove unwanted branches:

* --exclude-throw-branches removes branches that are used for exception handling, but this will also mess up coverage in a try/catch
* --exclude-unreachable-branches removes branches from lines that don't look like they contain any code, which typically indicates compiler-inserted code for static initialization.

Whether compiler-inserted branches should be counted towards your coverage target depends on your goals. Just want to cover the code that you wrote? Then largely ignore branch coverage. But if you want to ensure that a given binary works correctly in all situations, then it could make sense to try to test compiler-inserted branches as well.

**Comment by Diana-Lorena** [comment]
@latk Is there a way to remove this branches directly from the gcov options? I do not have the possibilities to install gcovr and use it. I thought there might be another way for this.

**Comment by latk** [comment]
No, gcov has no built-in way and post-processing is necessary. If you can't use gcovr: lcov is getting similar capabilities, see https://github.com/linux-test-project/lcov/pull/80 – I'm not sure though if it is already available in a release.

**Comment by Diana-Lorena** [comment]
@latk Thank you for the info. The new markers added for branch exclusion seem very useful, although I tried to put them as comments(as specified in geninfo.1) and nothing happened. As you said, maybe they are not available yet.
