### ISSUE TITLE
[Question] How to configure gcovr correctly for multiple test files

### ISSUE THREAD

**Issue by ahmedwahdan** [gcovr/gcovr#439]
I have a project with 10 modules. Each one has it's own testing report using google test.
Should I add coverage per test or the coverage is done per whole files?
How to configure it using CMake?

Thanks!

**Comment by latk** [comment]
There are no specific guidelines here – you can pick a workflow that makes sense for your project.

The gcovr/gcov/GCC coverage system does not know about individual tests, just about entire programs. When a program that was compiled with `--coverage` is executed, it writes coverage data to special files that gcovr will find and convert to a more usable output format.

To get per-test coverage data, you would have to run one test, collect coverage, then repeat with the next test. This can be useful if you need to understand which specific parts are covered by a single test.\
But most of the time, you will be interested in the coverage of your entire test suite. Whether you want one test report per module or only a single test report for your entire project is up to your preferences. For unit tests, you would likely prefer a separate report per module. If all modules share a build directory, it may be possible to use gcovr's --add-tracefile feature to combine multiple reports into a single report.

It's been some time since I last used CMake so I can't show example snippets.
