### ISSUE TITLE
Wrong function coverage

### ISSUE THREAD

**Issue by Diana-Lorena** [gcovr/gcovr#446]
Hello! 

Do you have any idea why I have some files with function coverage less than 100% when all the functions have been hit? It seems that gcov treats some branches as functions, and unfairly decreases my function coverage. Is there a way of solving this? Any gcc flag that could help maybe? I attached an example to see how big the line coverage is, but still the function coverage is very low even though all the functions are hit.

Thanks!
![image](https://user-images.githubusercontent.com/62993766/102239411-81c9ca00-3eff-11eb-9ff7-162a8bfa1679.png)

**Comment by latk** [comment]
This looks like an LCOV coverage report. Both lcov and gcovr (this project) use data from GCC's gcov mechanism, but lcov is otherwise an unrelated project. I don't know under which conditions they count functions for coverage. But I do know that GCC must necessarily inject lots of code, especially for static initialization. Such functions are real functions in the binary, they are just called before/after the main(). For C++, there might also be additional functions due to templates.

Gcovr has an option to exclude coverage from lines that don't look like contain any code, but gcovr does not support function coverage so that's not an option. Perhaps you could ask the lcov people what mechanisms they offer to exclude unwanted coverage?

**Comment by Diana-Lorena** [comment]
Thanks for the info! I will try to talk to the lcov guys.
