### ISSUE TITLE
Exclusion file: list of exclusions in file

### ISSUE THREAD

**Issue by macetw** [gcovr/gcovr#472]
**Is your feature request related to a problem? Please describe.**
It's good to be able to exclude files from the coverage report, but those exclusions should be definable in a file. If they are in a file, they can be clearly conveyed within a group and they can easily be reproduced without a large list of exclusions in command-arguments. It's just one argument, a location of a file.

The file should allow blank lines and have comments.

This comes from a mindset of "Infrastructure as code," that a list of exclusions would be committed into code and evolve with the code the team is generating coverage on.

Could this be yaml based? Maybe. I don't think it has to have a complex structure. It just needs to support regular expressions. A user might want to have an example of exclusions in a file in the documentation.

**Comment by latk** [comment]
I agree! that's why gcovr 4.2 supports [configuration files](https://gcovr.com/en/stable/guide.html#configuration-files), which are essentially a way to store command line arguments. Instead of writing `gcovr --exclude foo --exclude bar` you could put a `gcovr.cfg` file like this into your project's --root directory which will then be loaded by default:

```ini
# comments are supported
exclude = foo
exclude = bar
```

Note that relative filters will be interpreted relative to the location of the config file.

Why not YAML? I like YAML a lot, but it's not the simple and natural format that it looks like at first glance. I have yet to see two parsers that agree on all edge cases. I would have liked Python's built in INI format, but it doesn't support multiple entries per key. So I ended up implementing an INI-like custom format that explicitly reserves syntax for future extensions. E.g. we haven't yet committed to any approach to variable interpolation.

Config files are still marked as experimental since it's a complicated feature that's not well-used. While there may be breaking changes in the future if the design turns out to be bad, the feature was carefully designed for stability and future compatibility. If you have feedback from real-world usage, that would be most valuable.
