### ISSUE TITLE
Excluding files

### ISSUE THREAD

**Issue by pananton** [gcovr/gcovr#481]
Hello! Can you please explain why this error occurrs? I have libraryA and libraryB where libraryB depends on libraryA. Some headers/sources of libraryB `#include` headers from libraryA. LibraryA is installed in some outer directory (not on the system path or as a libraryB subdirectory). When I'm building libraryB test executable I can see that *.gcda and *.gcno files are generated as expected. Then after tests have run, I can launch gcovr for libraryB and obtain coverage report. The problem begins if libraryA source/header files are deleted or moved: gcovr outputs multiple error messages of the following view:
```
Cannot open source file <path-to-libraryA-header-file>
```

I've tried to exclude libraryA files from report with `--exclude` but it did not help me. Is there any way to make this work or presence of libraryA sources is a requirement (in that case can you explain, why it is a requirement)?

**Comment by latk** [comment]
Unfortunately, your use case is currently not supported.

The error message is generated by gcov, not gcovr. Due to the way how gcovr uses gcov, access to the source code is required. Here is a diagram of how gcov works:

![diagram, explained below](https://user-images.githubusercontent.com/1782927/112757960-6761bb00-8fdb-11eb-954d-29e978852839.png)

* When GCC compiles the source code with the `--coverage` flag, it generates object code and the `.gcno` file for that compilation unit, which maps counters to source code locations. This is similar to debugging symbols. The `.gcno` files hard-code a path to the sources.
* When the object code is executed, it will create a `.gcda` file with the counter data.
* We then use the gcov tool to create a `.gcov` report. This annotates each source line with coverage information. This requires the .gcda and .gcno files to get the raw coverage data, but also every source file from that compilation unit in order to create the annotated report.
* Gcovr then collects the `.gcov` reports and parses them. Only at this stage are filters applied.

While the gcov tool can generate reports without needing the source code (e.g. the old intermediary format or the GCC-9 JSON format), gcovr currently cannot read them.

**Comment by pananton** [comment]
Beautiful explanation, thanks a lot!
