### ISSUE TITLE
Build portable single executable

### ISSUE THREAD

**Issue by AbdManian** [gcovr/gcovr#486]
Is it possible to build a single executable for simpler distribution of the tool?
For example with use of pyinstaller build a single `gcovr.exe` (for windows) file and use it in without need of 
installing python and pip?

Note: I think this is useful only for Windows platform.

**Comment by latk** [comment]
Thank you for suggesting this. In principle this would be possible. But I don't think this is in-scope for the gcovr project.

* PyInstaller is great for end-user oriented applications. However, gcovr is a developer tool. I therefore believe it is reasonable to ask for Python to be installed in addition to GCC.
* Using a bundled application could pre-empt future directions such as plugin systems.
* Bundling means that we would be responsible for license compliance and security updates with respect to dependencies, which would be a substantial burden.

If a third party offers bundled gcovr executables I would be open to linking to them from the documentation. It would also be possible to commit a PyInstaller spec file to the gcovr repository so that downstream users can build their own executables, e.g. for distribution in an intranet.

I'd also be interested in what other people have to say. Maybe I don't see the importance of pre-built executables due to an overly Linux-oriented perspective.

**Comment by Spacetown** [comment]
@latk For the use of the upcoming version in my company I was also thinking about a standalone executable.
The problem is that we use IBM ClearCase and create a own workspace for each issue from scratch. Loading thousands of files is time consuming and the creation of the workspace takes sometimes about 90min. A standalone executable will save much time.
Maybe we can provide a configuration to build a executable with pyinstaller. I can start a PR next month.
