### ISSUE TITLE
Consider using gcov-dump to aid source file location?

### ISSUE THREAD

**Issue by inorton** [gcovr/gcovr#498]
Hi, I've been bumping up against #368 which seems to be an error in location the true source when running against out-of-source builds like those done with cmake.  About 75% of the time gcovr works fine with --html-details but sometimes it fails with the error in #368.

In trying to figure out what is going on more, I noticed the `gcov-dump` program.  When run on a gcda or gcno file this seems to produce very useful hints about the true location of source files.

Here is a dump from a gcno file:
```
$ gcov-dump-8 -lp ./cmake-build-dir/prog/src/CMakeFiles/mylib.dir/mylib.c.gcno
./cmake-build-dir/prog/src/CMakeFiles/mylib.dir/mylib.c.gcno:note:magic `gcno':version `A83*'
./cmake-build-dir/prog/src/CMakeFiles/mylib.dir/mylib.c.gcno:stamp 1551793849
./cmake-build-dir/prog/src/CMakeFiles/mylib.dir/mylib.c.gcno:    4:  01000000:  19:FUNCTION ident=1840490203, lineno_checksum=0xabfd92bc, cfg_checksum=0x7cb34af9, `nf_dstr_putf' ../mylib/mylib.c:393:5:401
./cmake-build-dir/prog/src/CMakeFiles/mylib.dir/mylib.c.gcno:   25:    01410000:   1:BLOCKS 5 blocks
<snip>
```
Here is a dump from the corresponding gcda file:
```
$ gcov-dump-8 -lp ./gcov-data/prog/src/CMakeFiles/mylib.dir/mylib.c.gcda
gcov-data/prog/src/CMakeFiles/mylib.dir/mylib.c.gcda:data:magic `gcda':version `A83*'
gcov-data/prog/src/CMakeFiles/mylib.dir/mylib.c.gcda:stamp 1551793849
gcov-data/prog/src/CMakeFiles/mylib.dir/mylib.c.gcda:    3:  a3000000: 482:PROGRAM_SUMMARY checksum=0x4fd985bd
gcov-data/prog/src/CMakeFiles/mylib.dir/mylib.c.gcda:    0:                counts=38575, runs=4, sum_all=1376078531, run_max=145630254, sum_max=377721747
gcov-data/prog/src/CMakeFiles/mylib.dir/mylib.c.gcda:    0:                counter histogram:
gcov-data/prog/src/CMakeFiles/mylib.dir/mylib.c.gcda:    0:                 0: num counts=32111, min counter=0, cum_counter=0
gcov-data/prog/src/CMakeFiles/mylib.dir/mylib.c.gcda:    0:                 1: num counts=468, min counter=1, cum_counter=468
gcov-data/prog/src/CMakeFiles/mylib.dir/mylib.c.gcda:    0:                 2: num counts=619, min counter=2, cum_counter=1238
<snip>
gcov-data/prog/src/CMakeFiles/mylib.dir/mylib.c.gcda:  970:  01000000:   3:FUNCTION ident=1840490203, lineno_checksum=0xabfd92bc, cfg_checksum=0x7cb34af9
gcov-data/prog/src/CMakeFiles/mylib.dir/mylib.c.gcda:  975:    01a10000:   4:COUNTERS arcs 2 counts
gcov-data/prog/src/CMakeFiles/mylib.dir/mylib.c.gcda:  977:                   0: 0 0
```
You can see that the `ident` values in the gcda files match all of the `ident` values in the gcno file. And the gcno file dump contains the relative source path on the end of the `FUNCTION` line. 

There are other types of data in the dumps that could be useful too.

**Comment by Spacetown** [comment]
This source path is the raw path stored in the gcno file and also need to be converted to the real path. You can copy the gcno to a different directory and will get the same result.

**Comment by latk** [comment]
I agree that this is unlikely to help, especially since the same path ends up in the .gcov file. The path `../mylib/mylib.c` has no clear base directory relative to which it could be resolved. It is NOT relative to the gcno or gcda. It is relative to the path where GCC was invoked, and (pre-GCC-9) that information is implicit in the build system. Knowing CMake, the following invocation should already do the right thing:

    cd cmake-build-dir; gcovr --gcov-executable gcov-8 -r ..

If the HTML-details report runs into problems with that, it would mean that we are internally storing the path incorrectly. That is the bug discussed by #368 etc.

Long term, solutions might include:

* using the extra working directory data provided by GCC-9
* using the GCC JSON format (added in GCC-9)
* parsing raw gcno/gcda files (probably easier than parsing gcov-dump output)

However, I don't expect to get around to it myself. Anything touching GCC-9 is also soft-blocked on untangling the test suite. While it now supports multiple compiler versions (so that adding GCC 9 tests is possible), it features unnecessary repetition that makes it a chore to keep in sync (scenario × output format × compiler matrix is very dense).

All in all: thank you for suggesting this approach. After careful consideration, I don't think it will lead to a solution. Therefore, I'm marking this as closed.
