### ISSUE TITLE
Possible bug in function coverage: assertion fails in some cases

### ISSUE THREAD

**Issue by erikbs** [gcovr/gcovr#511]
**Describe the bug**
The assertion on line 81 in coverage.py (i.e. `assert self.lineno == other.lineno`), introduced in commit 5b9cdec (30 July 2021), fails in some cases. We had issues with this in multiple projects before switching to release v5.0, but I only have details from one of them. In that project, the assertion would fail in the same file (a C++ header unique to this project), at the same line (discovered by adding debug printouts). The affected line was reached about 15 times, and the assertion failed 1-4 times per run (I assume that the thread-pool is the reason). When it failed, `self.lineno` and `other.lineno` were either 31 or 32, where line 32 contains a method definition and 31 is the empty line above it (line 30 is a destructor initialised to `default` and line 33 is another method definition). If the assertion failed multiple times in a run, `self.lineno` could be the same in all cases or it could be 31 in some cases and 32 in the rest.

The tracebacks (see below for examples) revealed that the assertion was reached from various different code paths. Unfortunately I was not able to strip down the project to create a minimal example (simple, irrelevant changes, such as deleting an unrelated source file or deleting the empty line, could make the problem go away), and I am not allowed to share the source code. I understand that with this little information it might be hard to debug the issue, but I am submitting a report anyway in case it contains enough information to put someone on the right track.

**To Reproduce**
1. Deleted the build directory
2. Built the project for coverage and ran tests that produced coverage data as usual
3. Ran a script that calls `gcovr` through Python, using the following command: `PYTHONPATH=${GCOVR_SRC} python3 -m gcovr --html --html-details -o ${BINDIR}/coverage/coverage.html --gcov-executable=${GCOV} -j 8 -s --root ${SOURCE_DIR} -- ${BINDIR}` (`GCOVR_SRC` is the root of the gcovr repo and the other environment variables are as one would expect).

**Expected behavior**
Preferably the assertion should not fail. If it is not possible to find the cause, I suggest that the report be produced without unhandled exceptions, e.g. by emitting a warning instead.

**Desktop (please complete the following information):**
 - OS: CentOS
 - GCC version 9, 10 and 11 (same results)
 - GCOVR version: master branch (per 30 July 2021)
 - Python: 3.6

**Additional context**
Traceback examples include (file paths anonymised):

```
Traceback (most recent call last):
  File "(...)/gcovr-src/gcovr/workers.py", line 76, in worker
    work(*args, **kwargs)
  File "(...)/gcovr-src/gcovr/gcov.py", line 685, in process_datafile
    error=errors.append, chdir=wd, tempdir=workdir)
  File "(...)/gcovr-src/gcovr/gcov.py", line 770, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "(...)/gcovr-src/gcovr/gcov.py", line 141, in process_gcov_data
    covdata.setdefault(key, FileCoverage(key)).update(parser.coverage)
  File "(...)/gcovr-src/gcovr/coverage.py", line 202, in update
    self.function(fct_name).update(fct_cov)
  File "(...)/gcovr-src/gcovr/coverage.py", line 81, in update
    assert self.lineno == other.lineno
AssertionError
```

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "(...)/gcovr-src/gcovr/__main__.py", line 462, in <module>
    main()
  File "(...)/gcovr-src/gcovr/__main__.py", line 284, in main
    collect_coverage_from_gcov(covdata, options, logger)
  File "(...)/gcovr-src/gcovr/__main__.py", line 354, in collect_coverage_from_gcov
    covdata[fname].update(cov)
  File "(...)/gcovr-src/gcovr/coverage.py", line 202, in update
    self.function(fct_name).update(fct_cov)
  File "(...)/gcovr-src/gcovr/coverage.py", line 81, in update
    assert self.lineno == other.lineno
AssertionError
```

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "(...)/gcovr-src/gcovr/__main__.py", line 462, in <module>
    main()
  File "(...)/gcovr-src/gcovr/__main__.py", line 284, in main
    collect_coverage_from_gcov(covdata, options, logger)
  File "(...)/gcovr-src/gcovr/__main__.py", line 346, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "(...)/gcovr-src/gcovr/workers.py", line 165, in __exit__
    self.wait()
  File "(...)/gcovr-src/gcovr/workers.py", line 156, in wait
    raise self.exceptions[0][1]
  File "(...)/gcovr-src/gcovr/__main__.py", line 346, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "(...)/gcovr-src/gcovr/workers.py", line 156, in wait
    raise self.exceptions[0][1]
  File "(...)/gcovr-src/gcovr/workers.py", line 76, in worker
    work(*args, **kwargs)
  File "(...)/gcovr-src/gcovr/gcov.py", line 685, in process_datafile
    error=errors.append, chdir=wd, tempdir=workdir)
  File "(...)/gcovr-src/gcovr/gcov.py", line 770, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "(...)/gcovr-src/gcovr/gcov.py", line 141, in process_gcov_data
    covdata.setdefault(key, FileCoverage(key)).update(parser.coverage)
  File "(...)/gcovr-src/gcovr/coverage.py", line 202, in update
    self.function(fct_name).update(fct_cov)
  File "(...)/gcovr-src/gcovr/coverage.py", line 81, in update
    assert self.lineno == other.lineno
AssertionError
```

**Comment by latk** [comment]
Thank you for this report! This is fascinating:

* either the compiler generates two functions with the same name on different lines, or
* in different compilation units, the compiler assigns different line numbers to the same function, or
* gcovr is getting confused because there are multiple headers with the same basename, or
* gcovr is assigning line numbers incorrectly.

If the assertion always failed at least once, this would point towards explanation 1 or 2 – it's GCC's or gcov's fault, but gcovr is doing a bad job of dealing with that flakiness. If the error disappears when you don't use `-j 8` (i.e., if gcovr uses its single-threaded mode, which is often faster anyway) then this points to explanation 4. I don't think explanation 3 is likely from the description of your problem, but only you know if there are multiple headers with the same name in different directories.

Another potential cause for explanation 4 is how gcovr determines the line number for a function. Gcovr parses the textual gcov report. A function annotation might look like this:

```plain
        -:   17:int
function main called 1 returned 100% blocks executed 81%
        1:   18:main (void)
```

(that example is from the GCC docs, so it uses the weird style of splitting the return type and the function name onto different lines)

Gcovr uses a single-pass parser. Its though process is this:

1. we are on line 17, but this can be ignored
2. a function tag! main() function is on line 17+1 = 18
3. we are on line 18 and this line is covered once

This works well, as long as the last seen line number is the previous line number! This fails … with templates. Gcov outputs a textual report like the following:

```plain
       1*:    7:  Foo(): b (1000) {}
------------------
Foo<char>::Foo():
function Foo<char>::Foo() called 0 returned 0% blocks executed 0%
    #####:    7:  Foo(): b (1000) {}
------------------
Foo<int>::Foo():
function Foo<int>::Foo() called 1 returned 100% blocks executed 100%
        1:    7:  Foo(): b (1000) {}
------------------
```

Thought process:

1. `1*: 7: ...`: we are on line 7 and this line is covered once
2. `----`: we are at the boundary of a template specialization section
3. `Foo<char>::Foo()`: this is the name of a specialization
4. `function ...`: a function tag! `Foo<char>::Foo()` is on line 7+1 = 8 (**wrong!!**)
5. `#####: 7: ...`: we are on line 7 and this line is uncovered

and so on. The point is that Gcovr's current parser is simplistic and will attribute function coverage of a templated function to line n+1 (or later, if the function body contains multiple lines). I have an idea to fix this, and this seems to be a bug regardless of the problem in this issue.

But could you confirm whether the function or class in question is templated? If template specializations were created in different orders in different compilation units, this *might* explain the problem. The function I'm suspecting is the destructor on line 30, not the method on line 32. But some degree of guesswork could be avoided if you patch the failing assertion to show the function name:

```diff
-            assert self.lineno == other.lineno
+            assert self.lineno == other.lineno, f"old line = {self.line}, new line = {other.lineno}, function = {self.name}"
```

**Comment by erikbs** [comment]
Thanks for the detailed response and explanations! I’ll start by summing up:

* Yes, the assertions seems to always fail at least once
* Removing `-j 8` does not fix the problem (the same goes for explicitly passing `-j 1`)
* Both the file and class names are unique in the project, but the class inherits from a base class
* The file in question does not contain any templates, but the common header includes other headers (from the standard library) that do (e.g. <string>)

I applied the patch you suggested (assuming that `self.line` was supposed to be `self.lineno`) and got the following printout (excluding the tracebacks):

```
AssertionError: old line = 31, new line = 32, function = Class::getType() const
AssertionError: old line = 31, new line = 32, function = Class::getType() const
AssertionError: old line = 31, new line = 32, function = Class::getType() const
```

I have anonymised the header file to give an idea of what it looks like (it is the `getType` method that fails):

```
// Comment
// Comment
// Comment
// Comment
// Comment
// Comment
#pragma once

#include "common_header.h"

class Class : public BaseClass
{
public:
   enum class Type
   {
      typeA,
      typeB,
      typeC,
      typeD
   };

   enum class Value
   {
      valueA,
      valueB,
      valueC
   };

   Class(Type type, std::string name, Value value);
   ~Class() override = default;

   [[nodiscard]] Type getType() const { return m_type; }
   [[nodiscard]] std::string getName() const { return m_name; }
   [[nodiscard]] State getValue() const { return m_value; }

protected:
   [[nodiscard]] BaseClass* newBasePointer() const override { return new BaseClass(*this); }

private:
   const Type m_type{Type::typeA};
   const std::string m_name;
   const Value m_value{Value::valueA};
};
```

We have other classes that inherit from the same base class, but this is the only one that has the issue. I removed the
[[nodiscard]] tags to see if that did any difference, but unfortunately it did not.

**Comment by latk** [comment]
I've been experimenting with a new parser, maybe it resolves the issue but given the available information I doubt it. I'll notify you when a branch is ready for testing.

At this point I'm more willing to blame GCC for this issue, but that opens the question of how to handle this in a fault-tolerant manner. What do you think would be more appropriate?

* Just pick either line number. If the number is picked in a consistent fashion (e.g. min or max, not last-one-wins) then reports will at least remain reproducible.
* Make the line number part of the function's identity – getType() on line 31 would be a different entity from getType() on line 32.

I don't think there's a “better” choice among these – both will skew the statistics since the underlying bug is just papered over. So I'd be interested in hearing opinions.

**Comment by Spacetown** [comment]
I'm wondering why the `Type` is missing in:
```
AssertionError: old line = 31, new line = 32, function = Class::getType() const
AssertionError: old line = 31, new line = 32, function = Class::getType() const
AssertionError: old line = 31, new line = 32, function = Class::getType() const
```
Is it possible that gcov  sometimes split the prototype to two lines with the same number?

**Comment by latk** [comment]
> I'm wondering why the `Type` is missing in `Class::getType() const`

The function name is not parsed from the source code, but is the demangled symbol name. In GCC's naming scheme, the return type is not part of the function name. So that part of the output is to be expected.

**Comment by latk** [comment]
While debugging my new gcov-parser, I stumbled upon a related problem. In our `excl-branch` test, we have the following code snippet (purposefully weird formatting):

```c++
class Bar
{
public:
    Bar()
    {}
    virtual ~Bar()
    {}

private:
    int m_param;
};
```

producing the following gcov file with GCC-8:

```gcov
        -:    4:class Bar
        -:    5:{
        -:    6:public:
function Bar::Bar() called 0 returned 0% blocks executed 0%
    #####:    7:    Bar()
    #####:    8:    {}
    #####:    9:    virtual ~Bar()
    #####:   10:    {} // possible compiler-generated destruction code - auto-detected and excluded
------------------
Bar::~Bar():
function Bar::~Bar() called 0 returned 0% blocks executed 0%
    #####:    9:    virtual ~Bar()
    #####:   10:    {} // possible compiler-generated destruction code - auto-detected and excluded
call    0 never executed
call    1 never executed
------------------
Bar::~Bar():
function Bar::~Bar() called 0 returned 0% blocks executed 0%
    #####:    9:    virtual ~Bar()
    #####:   10:    {} // possible compiler-generated destruction code - auto-detected and excluded
------------------
        -:   11:
        -:   12:private:
        -:   13:    int m_param;
        -:   14:};
```

There are multiple specialization sections for the destructor because GCC handles exceptional/non-exceptional destructors separately.

Now let's look at the `function` tags. Our old parser assigns the line number n+1 (as discussed in a previous comment), and thinks the destructor is on line **11**. This is completely wrong. The destructor is clearly on line **9**.

This is a different problem pattern from the one in this issue, but the presence of a destructor *just before* the offending line is highly suspicious. It also means my hunch about template specialization wasn't entirely wrong – I had just forgotten how GCC handles destructors.

My upcoming rewrite of the parser will not handle specialization sections correctly, but will associate function tags with the correct line number. I'm giving it a 50:50 chance of fixing this issue.

**Comment by erikbs** [comment]
That sounds great! I will test your new parser with our code tomorrow and report back.

Regarding this question:

> At this point I'm more willing to blame GCC for this issue, but that opens the question of how to handle this in a fault-tolerant manner. What do you think would be more appropriate?
> * Just pick either line number. If the number is picked in a consistent fashion (e.g. min or max, not last-one-wins) then reports will at least remain reproducible.
> * Make the line number part of the function's identity – getType() on line 31 would be a different entity from getType() on line 32.

I think both are acceptable. The first one has a good chance of picking the correct line number, but then the user will not know what happened and might wonder why the line number is incorrect if the parser picks the wrong number. Preferably a warning should be printed no matter how this is handled, but I *think* that with the second solution the user would be more likely to consult the log/printout to see what happened than with the first solution. On the other hand, I guess that the first solution is closer to what the user most likely wants.

**Comment by erikbs** [comment]
Good news: I tested our code with the new parser and it worked perfectly!
