### ISSUE TITLE
Percentage values in json-summary report

### ISSUE THREAD

**Issue by anotherandi** [gcovr/gcovr#517]
**Describe the bug**
In the json-summary report, the file-summary uses ratios in the attributes 'line_percent' and 'branch_percent'.
The value for full coverage is 1.0

**To Reproduce**
1. Generate a coverage report using the --json-summary-pretty reporter with any coverages.

**Expected behavior**
The value for full coverage should be 100.0 (i.e. a percentage value)

**Example output**
`
{
    "branch_covered": 2,
    "branch_percent": 100.0,
    "branch_total": 2,
    "files": [
        {
            "branch_covered": 2,
            "branch_percent": 1.0,
            "branch_total": 2,
            "filename": "impl/my_library/src/my_base_class.cpp",
            "line_covered": 6,
            "line_percent": 1.0,
            "line_total": 6
        }
    ],
    "gcovr/summary_format_version": "0.2",
    "line_covered": 6,
    "line_percent": 100.0,
    "line_total": 6,
    "root": "../../../../test"
}
`

**Comment by anotherandi** [comment]
First analysis:
* https://github.com/gcovr/gcovr/blob/9c88a8dd83da8be009d584529a687b7e4228f7cf/gcovr/writer/json.py#L91 uses summarize_file_coverage
* _summarize_file_coverage_ uses _fixup_percent_ (to get ratio values [0...1.0] instead of percentage which was only intended for csv files

**Comment by latk** [comment]
Yes, the summary report is inconsistent. I'm not entirely convinced whether [0,100] or [0,1] would be appropriate ranges in this context, but since it's a percentage I would expect the [0,100] range as well. Since the JSON formats are versioned, this can technically be changed without breaking backwards compatibility.

I have a branch somewhere that makes the coverage calculation clearer and would completely prevent such issues from reoccurring in the future. Then, fixing this issue would be a 1-line change. I'll open a PR once #515 is merged.

**Comment by Spacetown** [comment]
I've in mind that there was a discussion if 0.0 to 100 or  0.0 or 1.0 is correct. After searching I found this:
- https://github.com/gcovr/gcovr/pull/448#pullrequestreview-563776448
- https://github.com/gcovr/gcovr/pull/448#discussion_r554248329 and follow ups

**Comment by Spacetown** [comment]
I was to slow.
@latk If you approve I can close #515.
