### ISSUE TITLE
Support and additional information to use GCOVR

### ISSUE THREAD

**Issue by munnabhatia** [gcovr/gcovr#520]
1. There are 2 configurations for a file [trigger.c] due to a macro i.e #define TRIGGER which can have values ON and OFF [ and hence 2 configurations ]. By 2 configurations, it is meant that

a. Configuration 1 : trigger.c  -  #define TRIGGER ON
b.  Configuration 1 : trigger.c  -  #define TRIGGER OFF

Due to 2 different macros, different parts of code are enabled. But a consolidated coverage report is required, i.e which combines both coverage reports of configuration 1 and configuration 2 into a single report to show if any part of the code is missed to test.

Is this possible by directly using gcov and/or Gcovr and/or Gcov-tool and/or Gcov-dump?

2. Is it possible to check for coverage of a particular file? i.e in a project there are multiple files such as trigger.c , trigger_internal.c etc but consolidated coverage of only trigger.c is required.

Please advise how to proceed on these 2 queries

**Comment by soumyaranjansabat** [comment]
Yes, you are partially correct. Sharing a code snippet

**Configuration 1**
#define TRIGGER == ON

#if TRIGGER == ON
int sum(a,b)
#else
int mul(a,b)
#endif

**Configuration 2**
#define TRIGGER == OFF

#if TRIGGER == ON
int sum(a,b)
#else
int mul(a,b)
#endif

So a consolidated coverage [i.e combined coverage of configuration 1 and configuration 2] is required. So that it would show as 100% coverage. However, if only configuration 1 or configuration 2 coverage is checked it wouldn't be 100% coverage because of the enabled/disabled macro.
