### ISSUE TITLE
symbolic link, match error

### ISSUE THREAD

**Issue by marcaudefroy** [gcovr/gcovr#57]
Hello,

Thanks for your script, it's very usefu! :)

But since the v3.1, there is an error if the root dir is a symbolic link. 
Inside the method process_gcov_data at line: 

```
       if options.filter[i].match(fname):
           filtered_fname = options.root_filter.sub('',fname)
           break
```

For example : 
filter = \/private\/tmp\/myProject\/
fname = /tmp/myProject/../Tests/TestCases/Model/.../MyFile.m

/tmp is a symbolic link to /private/tmp (Mac OSX)

Any idea for fix this issue?

**Comment by latk** [comment]
This issue shows that the regex-based filters may not be optimal, or should perhaps only operate on paths that are relative or normalized in another way.

As a workaround, it should be possible to `cd "$(realpath .)"` prior to invoking gcovr so that gcovr always sees the real path, without symlinks. (This assumes you have GNU coreutils installed.)

I'd be interested in pull requests that address this issue. A PR should include:

 - an argument for what the “correct” behaviour would be, and whether a fix would break backwards compatibility.
 - a test case that reproduces this problem.
 - a fix in the code.

**Comment by Spacetown** [comment]
The filters are changed complete since v3.1. Please create a new issue if the problem persists.
