### ISSUE TITLE
Parsing gcov file fails on "Source is newer than graph" line

### ISSUE THREAD

**Issue by ovianao** [gcovr/gcovr#596]
**Describe the bug**
I can't provide much more detail, since it's an internal / private project, but I've nailed it down to the stack trace below and the following content in the gcov file along with gcovr 5.1, as we hit this line:

https://github.com/gcovr/gcovr/blob/e71e883521b78122c49016eb4e510e6da06c6916/gcovr/gcov_parser.py#L724

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gcovr/workers.py", line 77, in worker
    work(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 545, in process_existing_gcov_file
    process_gcov_data(filename, covdata, None, options)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov.py", line 100, in process_gcov_data
    metadata = parse_metadata(lines)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 226, in parse_metadata
    parsed_line = _parse_line(line)
  File "/usr/local/lib/python3.8/dist-packages/gcovr/gcov_parser.py", line 724, in _parse_line
    key, value = source_code.split(":", 1)
ValueError: not enough values to unpack (expected 2, got 1)

**To Reproduce**
1. ... Have a gcov file starting with these lines:
-:    0:Source:some_path_to_a_header_file.h  (in my case, gtest.h)
-:    0:Programs:3
-:    0:Source is newer than graph

**Expected behavior**
gcovr should parse the 3rd line.  Instead, it does not since it's expecting "Source is newer than graph" to be split-able by a ":".
Moving back to gcovr 5.0 allows us to go beyond the issue, since this change appears to have introduced it:
https://github.com/gcovr/gcovr/commit/304518453d352b21852e94f79ff78a4f4e4d2cb9

**Screenshots**

**Desktop (please complete the following information):**
    - Ubuntu 20.04
 - GCC version [e.g. MinGW 8.1.0]
   - gcov-5
 - GCOVR version [e.g. 4.2]
   - 5.1
 - Project directory layout:
   - private

**Additional context**

**Comment by latk** [comment]
Confirmed. Thanks for reporting this! Looking at the `gcov` source code (gcc 11), this message is the *only* case where the `-: 0:header:content` format is violated. It seems I had missed this case when writing the new parser.

Please consider pinning gcovr==5.0 until the issue can be resolved, or preferably: avoiding to change the source files before gcovr runs. While you'll still get accurate coverage statistics, coverage exclusion markers and the html-details report will be unreliable.

**Comment by Spacetown** [comment]
@latk There are also lines which are activated by options in function https://github.com/gcc-mirror/gcc/blob/50bc9185c2821350f0b785d6e23a6e9dcde58466/gcc/gcov.c#L3097 which use more `:`. This is interresting for projects which use existing gcov files.
Shall we ignore this lines and print a debug message?

**Comment by latk** [comment]
@Spacetown The other header lines like `Colorization: ...` will be handled correctly by the current `_parse_line()` function since they contain a `:`. But our `parse_metadata()` function won't quite work if there are multiple header lines with the same name. I think this doesn't matter though, because colorization information is not helpful or necessary for extracting coverage data (and the parser does not handle colorized reports at all because it doesn't strip out the ANSI escape codes).

So I don't think any additional changes are necessary.

With regards to the “source is newer than graph” line, I think it would be necessary to introduce a new line type since the `_parse_line()` function cannot skip lines. Maybe a `class _IgnoredLine`, and then silently ignoring it? Or we could transform it into a synthetic metadata field, e.g. `_Metadata("Source-newer-than-graph", "1")`, which would make it possible to produce a warning later in `gcov.py`.

**Comment by Spacetown** [comment]
Ah, I overlooked tha only the first `:` is split. A synthetic metadata field would be good but I prefer a value of None. Maybe gcov extend the line in the future.
At the moment I've problems with gcc-11 in our tests, gcc-10 was easy.
