### ISSUE TITLE
How should relative paths be treated in configuration files?

### ISSUE THREAD

**Issue by kkaja123** [gcovr/gcovr#609]
The [user guide for configuration files](https://gcovr.com/en/stable/guide/configuration.html) only states that "relative filters specified in config files will be interpreted relative to the location of the config file itself". Relative paths for other options are not explained in the documentation, but so far I've deduced that other paths would be relative to the working directory by default.

The code at configuration._get_value_from_config_entry() seems to suggest that there are some other options that can have path values but are also relative to the config file (such as those with the `check_input_file` type). I don't see that nuance documented in the configuration files user guide.

I believe that all relative paths in the configuration file should be relative to the file location for the sake of consistency, but is that the direction that this project should take? If that is the case, should every option that has a path or path list but is not currently relative to the file location be considered bugged (or saying it is a "todo" item sounds more appropriate)?

(The reason I ask is because I want to make sure that I understand the philosophy of configuration files for gcovr before propagating that philosophy to my coworkers' repositories.)

**Comment by Spacetown** [comment]
Thank you for reporting this inconsistency. I'll take a look at this next week.

**Comment by latk** [comment]
To clarify, yes, it is the intention that all file paths mentioned in a config file are resolved relative to the config file, so that the meaning of the config file does not depend on the gcovr working directory.

However, it seems that many path-related options don't respect this yet. A cursory glance suggests potential issues with the following fields:

* root
* add-tracefile
* search_paths
* (technically, gcov-executable)
* object-directory

**Comment by kkaja123** [comment]
Thank you for the clarification! That definitely answers my original question.
