### ISSUE TITLE
Is there a way to ignore macros for branch coverage measurement ?

### ISSUE THREAD

**Issue by onurctirtir** [gcovr/gcovr#619]
In other words, is there a way to tell gcovr to not investigate branches within macros ?

**Comment by Spacetown** [comment]
Not in general because the code isn't analyzed if the branch is the result from a macro.
There are two options to solve your problem:
- Use the option `--exclude-lines-by-pattern=PATTERN` to ignore the lines, e.g. --exclude-lines-by-pattern=".*(?:MACRO1|MACRO2|MACRO3)".
- Add a comment `/* GCOV_EXCL_LINE */` to the line where the macro is used.

**Comment by acki-m** [comment]
@Spacetown 
Why is adding `/* GCOV_EXCL_LINE */` necessary?
I mean this is the whole point of this exlucsion, that you do not need to add a marker everywhere in the code base.
Is there a way to exclude a macro with adding a additional comment everywhere in the codebase?

**Comment by Spacetown** [comment]
There where two suggestion, the first one is configuring the line by a matching RegEx (macro name) OR second one is using the comment.
