### ISSUE TITLE
Function coverage using GCOVR 

### ISSUE THREAD

**Issue by BadHermano** [gcovr/gcovr#622]
Hi all, 

i have a problem using the function coverage. 
I saw that there was the feature added for getting the coverage of a function but i cannot find the syntax for doing that. 

Can sb help me ?

**Comment by latk** [comment]
There is no special option to gather function coverage. If function coverage data is available in the input data, then it will be represented in the output formats. For example, since gcovr 5.1 the html-details report will contain a table that lists all functions in the file, and whether they were covered. You may have to click on the “list of functions” to see this list. Some other report formats only include aggregate function coverage. Some report formats like the default `--txt` output can't show this information at all.

**Comment by latk** [comment]
Unfortunately, function coverage just means “which functions are covered”, not “coverage metrics per function”. The underlying gcov data does not make the necessary information available, and it would be difficult to recreate afterwards. A simple heuristic might be “a function contains all lines until the next function”, but this cannot work for languages like C++, Objective-C or GNU C where functions can be nested. However, if that heuristic would be sufficient for your code base, then it might be possible to write a script that consumes gcovr's JSON output and calculates the relevant metrics.
