### ISSUE TITLE
Branch coverage overflow

### ISSUE THREAD

**Issue by AlexanderLanin** [gcovr/gcovr#624]
**Describe the bug**
It seems there is no overflow protection / detection.

**To Reproduce**
1. Run a piece of code with branches many many times in a loop

**Expected behavior**
Branch is reported as covered. Json shows something reasonable.

**Screenshots**
![image](https://user-images.githubusercontent.com/5074553/169548469-7d78e9a0-93d2-4c00-b18e-1c1ce56465a5.png)

**Desktop (please complete the following information):**
 - OS: WSL2 Ubuntu 20.04
 - GCC version: gcc10
 - GCOVR version: 4.2

**Additional context**
I'm not sure if this is a gcov or gcovr bug. But I guess in any case gcovr can easily detect the issue and deal with it properly.

Here is the json output for the line in question. As you can see the branch count is higher than the line count. And for one branch the count is negative which I interpret as an overflow. As shown in the screenshot this is then reported as uncovered branch.
```
{'branches': [{'count': 329793721, 'fallthrough': True, 'throw': False},
              {'count': -710, 'fallthrough': False, 'throw': False},
              {'count': 218484, 'fallthrough': True, 'throw': False},
              {'count': 329575237, 'fallthrough': False, 'throw': False}],
 'count': 329793011,
 'gcovr/noncode': False,
 'line_number': 60}
```

**Comment by latk** [comment]
I have yet to see an example .gcov file that exhibits the issue, but I'm 95% certain this is a problem in gcov. Gcovr is written in Python which features arbitrary-sized integers, making overflow or underflow impossible. Overflows in gcov are unlikely since the arc counters should be a `int64_t`, so my money is a memory corruption or race condition either in gcov, or within the instrumented binary.

> I guess in any case gcovr can easily detect the issue and deal with it properly.

What gcovr could do is to change the `covered = count > 0` criterion to `covered = count != 0`. But if we're seeing negative counts that indicates that the coverage data is untrustworthy in its entirety. There is no proper way to deal with corrupted data, other than maybe stopping with an error.

**Comment by Spacetown** [comment]
@AlexanderLanin Can you update or close the issue?

**Comment by AlexanderLanin** [comment]
Sorry, I'll try to reproduce after vacation. Please give me 10 more days.

**Comment by AlexanderLanin** [comment]
I cannot reproduce this in any reasonably small example. Attempted with one/multiple cpp files, one/multiple executables, different combinations of branches / function calls. In all cases branch counts of up to 18'000'000'000 work fine.

Stripping down existing code that produces this issue is unfortunately just too complex. And it seems it's not worth the effort as it doesn't appear in any simple setup. Maybe someone (future me) will stumble upon this issue via search function in case it’s still relevant.
