### ISSUE TITLE
Wrong Statement Coverage with variable definitions

### ISSUE THREAD

**Issue by BadHermano** [gcovr/gcovr#626]
Hi all, 

when i am calculating the coverage i am getting for some variable definition that the line is executed and for others that the line is not executed. 
Shouldn't all lines be executed ? see example below. 

       3:  345:    int test5[3] = {1 , 2 , 3};                                                      

        -:  346:    int test4 = (size_t)3 * sizeof(double);           

        3:  347:    double test3[18] = {0};                                               

        3:  348:    double test2[18] = {0};                                           

        3:  349:    int test1 = 0;                                                               

        -:  350:    unsigned int test = 1;

**Comment by latk** [comment]
Lines 346 and 350 are marked as “noncode”. In the test binary, there does not seem to be any executable code associated with those lines. I assume the compiler optimized those lines away e.g. because the variables are unused and/or the value is a compile-time constant.

Gcovr will not second-guess the compiler here. If the compiler says there's no executable code on that line, gcovr will ignore it. For calculating coverage metrics, these lines are excluded. For example, your code example would have 100% line coverage (4/4 lines).

If you really want to have these lines marked as “covered”, then we'd have to prevent the compiler from eliding those lines. This can usually be achieved by disabling all optimizations (e.g. `gcc -O0`). But sometimes basic optimizations (e.g. `-O1`) can produce “better” coverage reports, especially in C++. In particular, disabling optimizations can lead to lots of uncoverable branches. Ultimately, this is a matter of preference. Neither report is wrong, but raw metrics shouldn't be compared between optimization levels.

In some rare cases, the compiler's “coverage counter → source code” mapping is just incomplete, or subtly differs from the equivalent debug information. No way to fix that, except maybe using a different compiler version.

To understand how a particular snippet of code is seen by the compiler, I often look at the generated assembly code with the [Godbolt compiler explorer](https://godbolt.org/). With the `--coverage` option, you can see that GCC inserts instructions to increment counters at the beginning of each basic block/branch target. Since your code snippet doesn't contain any branches, you'll see that there is only one counter for all lines. So if there was executable code on that line (which will be the case with `-O0`), then it would also be shown as covered with three executions.
