### ISSUE TITLE
(WARNING) Unrecognized GCOV output

### ISSUE THREAD

**Issue by martaiborra** [gcovr/gcovr#627]
Hi, I issued a possible problem when running linux-release coverage with 
ubuntu-18.04
GNU 7.5.0
-- CMake version: 3.23.1

It can compile and all tests pass, but  the following error happens.

```
Starting: Create coverage report
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.201.1
```

```
(WARNING) Unrecognized GCOV output for /home/vsts/work/1/s/src/iarray_views.c
	  function prop8_view_postfilter called 8092 returned NAN % blocks executed 19%
	  function slice_view_postfilter called 34888 returned NAN % blocks executed 18%
	This is indicative of a gcov output parse error.
	Please report this to the gcovr developers
	at <[https://github.com/gcovr/gcovr/issues>.](https://github.com/gcovr/gcovr/issues%3E.)
(WARNING) Exception during parsing:
	UnknownLineType: function prop8_view_postfilter called 8092 returned NAN % blocks executed 19%
(WARNING) Exception during parsing:
	UnknownLineType: function slice_view_postfilter called 34888 returned NAN % blocks executed 18%
```

I would appreciate if you could tell me how to fix this.
Thanks in advanced!

**Comment by latk** [comment]
Confirmed. [In GCC 7.5.0, gcov reports a 0/0 ratio as `NAN %`.](https://github.com/gcc-mirror/gcc/blob/b2d961e7342b5ba4e57adfa81cb189b738d10901/gcc/gcov.c#L1962-L1967)

As a temporary fix, you can use the `gcovr --gcov-ignore-parse-errors` option to generate reports despite this warning message. The report will be entirely correct, except that these functions will be missing from the function coverage table. You are possibly already using this option, otherwise the warning message would have informed you about it.

As a permanent fix, gcovr will eventually be updated to support this aspect of the GCC 7.5.0 format. This is probably just a patch in gcov_parser.py:

```diff
-    pattern = pattern.replace("VALUE", r"[0-9.]+[%kMGTPEZY]?")
+    pattern = pattern.replace("VALUE", r"(?:NAN |[0-9.]+)[%kMGTPEZY]?")
```

**Comment by martaiborra** [comment]
Perfect, that works! Thank you for your quick response!

**Comment by Spacetown** [comment]
@latk Shall we continue on NAN or can we close this issue? If I shall adapt the parser, is NAN equal to 0?
