### ISSUE TITLE
Confusion about filters/exclude

### ISSUE THREAD

**Issue by TFA-N** [gcovr/gcovr#658]
Hi,
I've been having issues with gcovr seemingly not excluding files/directories from coverage that I want excluded. I read two other Issues on here about similar problems, but still didn't manage to solve my problem. I hope you guys can help me and I appreciate any time you can spare!

My project has a structure like this
SourceDir1/
SourceDir2/
3rdparty/

For building, I create a folder build, run cmake, build and then run my tests. So when I invoke gcovr, the structure looks like this
SourceDir1/
SourceDir2/
...
SourceDirN/
3rdparty/
build/

The build process autogenerates a whole bunch of .cpp files inside the build dir, which I want to exclude. I also want to exclude 3rdparty/ and essentially anything not inside SourceDir1 through SourceDirN from influencing coverage.

I invoke gcovr in the build dir: `gcovr -r .. -e '.*build\/.*' -e '.*3rdparty\/.*' --gcov-exclude '.*build\/.*' --gcov-exclude '.*3rdparty\/.*'  --txt`
To my understanding, this should filter all autogenerated and 3rdparty source files. However, in the summary I can see that many source files in build/ are included in the report. This leads to a tremendous amount of warnings about not being able to open source files and such for these autogenerated sources, e.g.: 
`/builds/project/build/SourceDir1/CMakeFiles/SourceDir1_Target.dir/SourceDir1_Target_autogen/mocs_compilation.cpp.gcda:cannot open data file, assuming not executed`
`Could not open output file 'moc_Client.cpp##99a936760e451d0b164a0c7c8a6cf1ee.gcov'` 
(List keeps going on for all dependencies of the autogen code)  

I'd appreciate any clarification or hints about where I am going wrong with this, and I will happily volunteer to write some examples to the documentation of filters/exclude to help others in the future once I understand how this works :)

Cheers,
Tom

**Comment by TFA-N** [comment]
I am using gcovr 5.2, if that matters.

**Comment by latk** [comment]
The [*Using Filters* chapter of the user guide](https://gcovr.com/en/stable/guide/filters.html) explains:

> A filter is a regular expression that matches a file path. […]
> 
> If the filter looks like an absolute path, it is matched against an absolute path. Otherwise, the filter is matched against a relative path, where that path is relative to the current directory or if defined in a configuration file to the directory of the file.

The filter `-e '.*build\/.*'` looks like a relative path. But you are within the build directory, so that the relative path to other files in the build directory won't contain the `build` name!

For example, you might want to exclude `build/autogenerated.cpp`. The relative path to this file (relative to the current working directory) would be `autogenerated.cpp`, not `../build/autogenerated.cpp`.

There are different ways to fix this.

* If you are on a Unix-like system, you could use a regex that matches an absolute path, for example `-e '/.*/build/'`.
* You could add a `--filter '\.\./'` option, so that only files outside of your build directory are considered. This is subtly different to the `--root ..` option, in that the --filter is a regex that matches (relative) path names, whereas the --root filter is converted to an absolute path before matching. Since the build directory is part of your root directory, those files were still included in the reports.
* You could put the exclude patterns into a `gcovr.cfg` file in your project root. Filters in config files are interpreted relative to the file. For example:

  ```ini
  exclude = build/
  exclude = 3rdparty/
  ```

  ```bash
  gcovr -r .. --txt # config file is picked up automatically in the root directory
  ```

You do not need the `--gcov-exclude` filters. These are most useful when running gcov yourself, but can also be used to speed up coverage data search. That's more of an advanced feature.

**Comment by TFA-N** [comment]
Thank you for the clarification. I added a gcovr.cfg as you proposed (a very handy feature!). However it seems that coverage for sources that only exist in build is still included.
```
(WARNING) GCOV produced the following errors processing /builds/lighting-consoles/build/CMakeFiles/3.16.3/CompilerIdCXX/CMakeCXXCompilerId.gcno:
    /builds/bretgeld-engineering/project/build/CMakeFiles/3.16.3/CompilerIdCXX/CMakeCXXCompilerId.gcda:cannot open data file, assuming not executed
Cannot open source file CMakeCXXCompilerId.cpp
```
`CMakeCXXCompilerId` is autogenerated by CMake and doesn't exist outside of build/, so from my understanding it should be excluded. I experimented with adding `--gcov-exclude '.*CMakeFiles.*'` but this didn't exclude anything

As for the Documentation, with your permission I would like to add the following to Filter Options:
- Link to the config file docu 
- Add your examples to exclude build folder via absolute/relative path (Judging by the other issues, it seems to be a common problem)

**Comment by TFA-N** [comment]
Thank you for the clarification. I added a gcovr.cfg as you proposed (a very handy feature!). However it seems that coverage for sources that only exist in build is still included.
```
(WARNING) GCOV produced the following errors processing /builds/project/build/CMakeFiles/3.16.3/CompilerIdCXX/CMakeCXXCompilerId.gcno:
    /builds/project/build/CMakeFiles/3.16.3/CompilerIdCXX/CMakeCXXCompilerId.gcda:cannot open data file, assuming not executed
Cannot open source file CMakeCXXCompilerId.cpp
```
`CMakeCXXCompilerId` is autogenerated by CMake and doesn't exist outside of build/, so from my understanding it should be excluded. I experimented with adding `--gcov-exclude '.*CMakeFiles.*'` but this didn't exclude anything

As for the Documentation, with your permission I would like to add the following to Filter Options:
- Link to the config file docu 
- Add your examples to exclude build folder via absolute/relative path (Judging by the other issues, it seems to be a common problem)

**Comment by latk** [comment]
The error message you are seeing is caused by GCC-gcov. 

While these exclusions prevent coverage from appearing in a report, we still have to process the coverage data in order to apply filters. Each .gcno/.gcda file with raw coverage data can contain information about any number of source files. Here is a diagram of GCC-gcov's coverage processing pipeline:

![](https://user-images.githubusercontent.com/1782927/124289139-83787980-db41-11eb-9d24-23beb5257a2a.png)

Gcovr runs GCC-gcov, and then consumes the generated reports. The reports also include the file name, which allows us to apply filters. So filtering options like `--filter`, `--exclude`, `--root`, `--gcov-filter`, `--gcov-exclude` only apply *after* GCC-gcov has already generated reports.

If you know for sure that the .gcno/.gcda files in a particular directory will be irrelevant, you can exclude such directories though. Unfortunately the filters here are less developed, but `--exclude-directories '(.*/)?CompilerIdCXX/'` should work.

**Comment by latk** [comment]
> As for the Documentation, with your permission I would like to add the following to Filter Options:
> 
>    * Link to the config file docu
> 
>    * Add your examples to exclude build folder via absolute/relative path (Judging by the other issues, it seems to be a common problem)

Yes, feel free to extend the documentation.

The *Using Filters* section of the guide could get an example section, or you could write a cookbook entry (and link it from relevant places).

The *Filter Options* section in the *Command Line Reference* is a bit tricky though. This text is managed in `configuration.py`. It must render reasonably as the plaintext `gcovr --help` message on the command line, but also as reStructured Text when included via Sphinx-Doc on the website.
