### ISSUE TITLE
Gcovr fails sometimes with "string index out of range"

### ISSUE THREAD

**Issue by ragnarruutel** [gcovr/gcovr#66]
Here's full call stack:

Traceback (most recent call last):
  File "/usr/local/build-system/cpp/tools/gcovr/scripts/gcovr", line 1961, in <module>
    process_datafile(file_,covdata,options)
  File "/usr/local/build-system/cpp/tools/gcovr/scripts/gcovr", line 749, in process_datafile
    process_gcov_data(fname, covdata, options)
  File "/usr/local/build-system/cpp/tools/gcovr/scripts/gcovr", line 507, in process_gcov_data
    if tmp[0] == '-' or (excluding and tmp[0] in "#=0123456789"):
IndexError: string index out of range

What might cause it?

**Comment by joschen** [comment]
same issue here:
Built target radio_gcov_xml
Traceback (most recent call last):
  File "/var/fpwork/hztdci01/workspace/1.2_UTMT/BTS_SC_TDD_CPRI_H/testing/unit/tools/gcovr.py", line 1837, in <module>
    process_datafile(file,covdata,options)
  File "/var/fpwork/hztdci01/workspace/1.2_UTMT/BTS_SC_TDD_CPRI_H/testing/unit/tools/gcovr.py", line 739, in process_datafile
    process_gcov_data(fname, covdata, options)
  File "/var/fpwork/hztdci01/workspace/1.2_UTMT/BTS_SC_TDD_CPRI_H/testing/unit/tools/gcovr.py", line 495, in process_gcov_data
    if tmp[0] == '-' or (excluding and tmp[0] in "#=0123456789"):
IndexError: string index out of range

and seems i change another server to run, it works well.

**Comment by latk** [comment]
Hmm, these error reports suggest that some gcov versions leave the first column in their reports empty, like

      : 7: foo()

where we would usually expect

    -: 7: foo()

We can't fix that without knowing exactly what's happening, but we could change the parsing code to fall through to the “Unrecognized GCOV output” case if the first column is empty.

If anyone else encounters this problem, please:

 - tell us which gcov version you are using.
 - if possible, provide the .gcov file that led to this problem.

**Comment by latk** [comment]
In #228, a `--gcov-ignore-parse-errors` option has been added that will allow you to continue despite such errors. You will still get a warning message. If anyone can contribute a real-world example that would be great, because I can then fix the cause of this error instead of just concealing these problems.

**Comment by ulyasutay** [comment]
This has happened to me.  In my case it is caused by the source file having messed up line endings (someone has edited it in Windows).  As far as I can see, Python treats both \r and \n as a line delimiter so when the line ends with \r\n, Python sees a blank line.  So the gcov output contains the line:
  -:  33:\r\n
Python interprets this as -: 33: on one line, followed by a blank line.  When gcovr tries to process the blank line, it calls parse_code_line with status==''.  The exception is caused by trying to access status[0].

**Comment by latk** [comment]
Thank you @ulyasutay for that info. I see that the code accessing `status[0]` does not check whether the input line is well-formed, however I cannot reproduce the problem with CRLF line endings using Python 3.6. Python should be reading the gcov file in “universal line ending” mode that accepts both \n and \r\n interchangeably.

As this is not happening for you, please consider opening a separate issue with more info about your system (operating system, Python and Gcovr versions, and `gcovr --verbose` output for debugging). In the meanwhile, note that you can `--gcov-ignore-parse-errors` to carry on despite such exceptions.

**Comment by ulyasutay** [comment]
I was using python 2.6.6.  I have tried running it in python 3.5.1 and it works properly.
