### ISSUE TITLE
--decisions not effective in C switch statements

### ISSUE THREAD

**Issue by shadazar** [gcovr/gcovr#665]
**Describe the bug**
When trying to show decision coverage for switch statements, it does not seem to properly recognize when a case is taken.

**To Reproduce**
I'm seeing this problem on all C switch statements in my code base

**Expected behavior**
Either the coverage decision markers on the left side to not be there, or them to report coverage properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/16995379/187552524-3e48f23a-ceb7-4772-a92f-873085973943.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GCC version: gcc-linaro-7.4.1-2019.02-i686-mingw32_aarch64-linux-gnu
 - GCOVR version 5.2

**Comment by latk** [comment]
Ok, yes, that seems like a bug in the decision coverage analysis. Slightly simplifying things, the code for the switch coverage analysis is

```python

    def parse_one_line(self, lineno: int, code: str) -> None:
        line_coverage = self.coverage.lines.get(lineno)

        if line_coverage is None or line_coverage.noncode:
            return

        ...

        # check if it's a case statement (measured at every line of a case, so a branch definition isn't given)
        if _is_a_switch(code):
            if "; break;" in code.replace(" ", "").replace(";", "; "):
                # just use execution counts of case lines
                line_coverage.decision = DecisionCoverageSwitch(line_coverage.count)
            else:
                # use the execution counts of the following line (compatibility with GCC 5)
                line_coverage_next_line = self.coverage.lines.get(lineno + 1)
                if line_coverage_next_line is not None:
                    line_coverage.decision = DecisionCoverageSwitch(
                        line_coverage_next_line.count
                    )
```

Evidently, the heuristic is trying to handle single-line cases like `case FOO: do_something(); break;`. That case cannot trigger here.

So the coverage data is taken from the next line. Until including gcovr 5.2, there's a concept of “noncode” lines that exist in the data model but are otherwise ignored. Here, the next line is a C-style comment, which qualifies for “noncode” status. The line was executed zero times because it doesn't contain any code. But the decision analysis fails to check for noncode status…

I'm not entirely sure how to fix this. Possibly, the correct approach is to scan forward until the next line with usable coverage data, for example:

```python
if _is_a_switch(code):
  for next_lineno in range(lineno, max(self.coverage.lines, lineno + 1)):
    line_coverage_next_line = self.coverage.lines.get(next_lineno)
    if line_coverage_next_line is not None and not line_coverage_next_line.noncode:
      line_coverage.decision = DecisionCoverageSwitch(line_coverage_next_line.count)
```

But that would be problematic if it reads past a `break` or past the end of a switch.

In the meanwhile, I would suggest to not use `gcovr --decisions`. While it is intended to provide a more interpretable alternative to “branch coverage”, the truth is that the decision analysis uses a bunch of very fragile heuristics. And as we see in bug reports like this, the heuristics do break even in some simple cases.
