### ISSUE TITLE
JSON backwards compatibility

### ISSUE THREAD

**Issue by solemnwarning** [gcovr/gcovr#668]
Hello,

I have a mixed C++/Lua project that I was generating coverage reports for using gcovr normally for the C++ parts and importing the Lua coverage data using https://github.com/jprjr/luacov-reporter-gcovr.

As of 5.2 the JSON format version has been bumped to 0.3 and files in the 0.2 format (generated by luacov-reporter-gcovr) aren't supported. Is the intent of the JSON importer to _only_ work with files produced by the same version of gcovr rather than consuming data from other tools?

Additionally, the manual doesn't seem to actually describe how the format has changed over time - the JSON format described in the 4.2 manual is the same as the one described in the 5.2 manual.

Thanks

**Comment by latk** [comment]
Currently, gcovr only supports `-a/--add-tracefile` for JSON files that it generated itself. While I don't want to put any obstacles in the way of third party input generators, I don't want gcovr to commit to a particular JSON structure right now. Thus, the format version number is `0.x` (not yet stable!) and checked for an *exact* match.

In practice, you can probably write a script to fix up the JSON generated by a third party tool by adding empty entries for newly added sections – but I'd have to look at diffs between releases to know what exactly changed. As far as I can tell:

* 5.2 introduced no visible changes
* 5.1 bumped the format version to `0.3`
  * introduced the per-line `gcovr/excluded` field
  * introduced the per-line `gcovr/decisions` field
  * introduced the per-file `functions` object

Eventually, gcovr will learn to support the upstream GCC gcov JSON format, which is more stable. See #282.

A significantly improved documentation for the gcovr JSON format is part of #663. Yes, documentation for additions to the format were neglected. But since the format documentation is mainly intended for *consumers* of this format, the lack of documentation also communicates an expectation of instability :)

I'd love to see a pull request with better help messages for the command line options themselves.

**Comment by solemnwarning** [comment]
Thanks for clearing that up, and pointing out exactly what changed in the 0.3 format. For anyone else having this issue, this shell one-liner fixed up the output from luacov-reporter-gcovr enough for gcovr 5.2 to import it:

```
cat luacov.report.out \
    | jq '."gcovr/format_version" = "0.3"' \
    | jq '.files[].functions = []' \
    | jq '.files[].lines[]."gcovr/excluded" = false' \
    > luacov.report.fixed
```
