### ISSUE TITLE
feature: add side frame which shows functions outline for html output

### ISSUE THREAD

**Issue by jiushen** [gcovr/gcovr#68]
when you click a foo.cpp to view its detailed coverage, you should keep scrolling down to the specified function you want to see.
just like that we can navigate to the specified function easily with a outline of functions in IDE like eclipse.
is it a reasonable feature?

**Comment by latk** [comment]
Thank you for this suggestion. However, a function outline would require gcovr to actually parse the source code in order to find function definitions. That would be a massive expansion of scope. I am not comfortable with that.

However, the gcov output can already include function-level coverage summaries. If those can be extracted, then a table of functions can be included in the HTML report. This may not work like your suggested outline, but would definitively be a large improvement.
