### ISSUE TITLE
Backwards compatibility for older gcov branch syntax to support uVision Keil coverage output.

### ISSUE THREAD

**Issue by JeffLCL** [gcovr/gcovr#697]
We use gcovr to generate coverage reports from gcov files output by uVision Keil debugger, but gcovr after v4.2 cannot parse the branch syntax in the gcov files. It appears gcovr has deprecated support for older branch syntax in after 4.2.

We'd like to request backwards compatibility to support the legacy branch syntax, if possible.

The old branch syntax looks like this example (excerpt of a gcov file):
    19:   113:    if ((f_mode_g == f_mode_inner)||(f_mode_g == f_mode_outer))
branch 0 executed 1
branch 1 skipped 1
branch 2 executed 1
branch 3 skipped 1
branch 4 executed 1
branch 5 skipped 1
branch 6 executed 1
branch 7 skipped 1

The newer syntax is described in the comments of the gcovr v5.2 file, gcov_parser.py (line 850) as:
    # BRANCH
    #
    # Structure:
    # branch BRANCHNO never executed
    # branch BRANCHNO taken VALUE
    # branch BRANCHNO taken VALUE (ANNOTATION)

If you can't restore support for this syntax, then could you provide an explanation of how the older syntax maps to the new so we can implement a conversion script ourselves?

**Comment by Spacetown** [comment]
We support gcov syntax and with #621 we already added a workaround to support the uncovered markers. If the format produced by the debugger differs in this way here I suggest to preprocess the files with a sed command to produce correct gcov format and raise a bug report for the `uVision Keil debugger`.

**Comment by JeffLCL** [comment]
Thanks for the reply.
https://github.com/gcovr/gcovr/issues/621 addresses the Keil gcov 6-character ###### marker instead of GCC's 5-character marker for uncovered lines, but this issue relates to incompatible branch makers.
That said, I was able to do a simple search and replace, replacing "executed" and "skipped" with"taken" in the gcov's produced by Keil and was able to generate coverage reports with gcovr v5.2 that had identical coverage results to coverage report generated by gcov v4.2 with unmodified Keil gcov's.
This seems to resolve the issue.

**Comment by Spacetown** [comment]
The old behavior was to to take everything which doesn't match `branch <x> never executed` as number of executions. E.g `branch 1 skipped 1` was counted as branch 1 taken 1 times. If I understand your listing correct, this was wrong.
You should create a support ticket (with link to #621 and this issue) because in their [documentation](https://developer.arm.com/documentation/101407/0537/Debug-Commands/COVERAGE/COVERAGE-GCOV-Export?lang=en) they refer to the documentation of [gcov](https://gcc.gnu.org/onlinedocs/gcc/Gcov.html) where the [format](https://gcc.gnu.org/onlinedocs/gcc/Invoking-Gcov.html#Invoking-Gcov) is specified. For the branch coverage they use their own format:
```
branch (seq_number) executed {0|1}    // marks branch path taken: false=0, true=1
branch (seq_number) skipped {0|1}     // marks branch path not taken: false=0, true=1
```

In the documentation they show a report for:
```
branch 0 executed 1
branch 1 skipped 1
branch 2 executed 1
branch 3 skipped 1
branch 4 executed 0
branch 5 skipped 1
```
Branch 4 has a red cross here but branch 1, 3 and 5 have a green check but for me a skipped=true should also be a red cross.
