### ISSUE TITLE
switch issue

### ISSUE THREAD

**Issue by johvik** [gcovr/gcovr#71]
With the following code I expect to get 100% branch coverage:

``` c
#include <stdio.h>

void do_switch(int len) {
    switch (len & 1) {
        case 1:
            printf("one\n");
            break;
        case 0:
            printf("zero\n");
            break;
    }
}

int main() {
    do_switch(1);
    do_switch(0);
    return 0;
}
```

But it claims that I missed one branch.

Changing `case 0:` to `default:` gives the expected results.

**Comment by latk** [comment]
Gcovr does not understand your code, it just reports coverage results. So if your compiler with the optimizations you have chosen emits an extra fall-through branch because it cannot recognize that one of the cases must apply, that's an issue with the compiler and not with gcovr.

Note that gcc/gcov thinks about coverage in terms of machine code instructions, not in terms of language-level control flow constructs. The coverage results tend to get confused with inlined functions, optimizations, and C++ destructors.
