### ISSUE TITLE
Why functions-covered and functions-valid are removed from the report?

### ISSUE THREAD

**Issue by slavko-m** [gcovr/gcovr#794]
Hi,

I see that in [this commit](https://github.com/gcovr/gcovr/pull/671/commits/09ad2f3d024cb227175b1ecab2aafc816fc34d5e) `functions-covered` and `functions-valid` are removed from the report. I was using this info in my script with old version of gcovr. Now, when I updated gcovr, I don't have this info. Why is it removed? Is it possible to get this info somewhere else?

**Comment by Spacetown** [comment]
As mentioned in the [PR comment](https://github.com/gcovr/gcovr/pull/671#issue-1368321435) this attributes are not allowed by the [schema](http://cobertura.sourceforge.net/xml/coverage-04.dtd). If you need this information you can use the CSV or JSON format.

**Comment by gsemet** [comment]
Isn’t it possible to let this feature as an option? We need this information and we have lost this feature.

**Comment by Spacetown** [comment]
No. The attributes are not allowed by the schema.

**Comment by latk** [comment]
@gsemet Is there any particular publicly available software that uses these fields? If possible gcovr avoids breaking stuff, but here the mere presence of these options is doing harm because they are disallowed by the Cobertura XML schema.

Maintaining an option for a Cobertura dialect is a lot of work. Implementing it is quite easy, but testing and maintaining it in all eternity is not.

The gcovr JSON reports are easier to consume for downstream tools, and they include everything that gcovr knows (except the contents of source files). You probably want the `function_total` and `function_covered` fields in the [`--json-summary` report](https://gcovr.com/en/main/output/json.html#summary-statistics). While gcovr doesn't commit to the long-term stability of this format, the summary-format is pretty stable and we include a SemVer-compatible format version number.

**Comment by gsemet** [comment]
That ok for me, I’ll just switch to the json, I just discovered it when I updated the tools in our internal tool chain. JSON is indeed way simpler to parse :)
