### ISSUE TITLE
From .gcda & ,gcno to XML or HTML, how does gcovr do it??

### ISSUE THREAD

**Issue by zhuliang1989** [gcovr/gcovr#81]
My gcovr version is gcovr-3.2, there are mainly 5 functions in the source code,. the followings :

1:    def get_datafiles(flist, options):    line:322   to get gcda & gcno  files
2:   def process_gcov_data(file, covdata, options):     line:347   process the data of gcda & gcno

3:   def process_datafile(filename, covdata, options):  line:472   the most important one for processing data 

4:   def print_text_report(covdata):   line:616   Produce the classic gcovr text report

5:    def print_xml_report(covdata):   line:666   Produce an XML report in the Cobertura format

I want to know how does gcovr   provide the XML report  or  HTML report , which function , which line, ????        Because python is too hard for me

**Comment by 11005844** [comment]
If I understand correctly you wish to know the flow of the gcovr python script only.
The flow of functionality is fairly simple, if you have programming experience of any kind. To follow this you can use any test editor like notepad++(since its free) or any python editor.
It is also very simple to add and print debug messages for your test as
              sys.stdout.write("<YOUT MESSAGE> %s\n" % <VARIABLE>) 
where ever you need. This will give you information on the "gcovr" python script.
You can also use the existing debug messages provided with -v option.

The script has pre defined tags for each case (XML and HTML) and generates the output file accordingly. If you are asking how that information is generated, then I believe its around 740 (I have a few updates in mine so line number may differ) or search for string "(out, err) = subprocess.Popen"
