### ISSUE TITLE
Gcovr asked me to report this to the gcovr developers

### ISSUE THREAD

**Issue by Myrkiriad** [gcovr/gcovr#82]
Here is the error message I get:

This is indicitive of a gcov output parse error.
Please report this to the gcovr developers.(WARNING) Unrecognized GCOV output: '$$$$$'

In my .gcov file, I have things such as:

call    5 returned 100%
call    6 returned 100%
call    7 returned 100%
    $$$$$:   14-block  3
branch  8 never executed
branch  9 never executed
    $$$$$:   14-block  4
call   10 never executed
    $$$$$:   14-block  5
call   11 never executed

I am using:
gcov (GCC) 4.1.2 20080704 (Red Hat 4.1.2-48)

**Comment by Myrkiriad** [comment]
I am using the option -a for gcov and option -g for gcovr.
It seems that option -a is not weel supported by gcovr when using -g.

How to use gcov when using -g option for gcovr is not well documented.

**Comment by latk** [comment]
I can reproduce this issue. So far, multiple blocks per line are simply not supported.

But I would like to see pull requests that address this use case. This will be rather difficult because it may require changes to the text, xml, and html output formats and to the internal gcovr data structures. Even partial solutions (e.g. code to parse these blocks but warn that they are unsupported) are welcome.

**Comment by latk** [comment]
Since gcovr 5.1, gcov files with block coverage information can be parsed successfully, though the information is not included in any coverage reports.

**Comment by Spacetown** [comment]
@latk That's fine. Nevertheless I would suggest to add a test for this. What do you think?

**Comment by latk** [comment]
There are a couple of tests to make sure that the parser handles these cases, though no full integration test.

https://github.com/gcovr/gcovr/blob/1040a85ecfb3ef0d01635df9d50a3cae5059d566/gcovr/gcov_parser.py#L731-L740

**Comment by Spacetown** [comment]
I think, that's enough.
