### ISSUE TITLE
Cobertura: missing support for function coverage

### ISSUE THREAD

**Issue by RoadTrain** [gcovr/gcovr#843]
Currently Cobertura reporter does not fill the `<methods>` element, leaving it blank. The reasoning for that is as folows:
https://github.com/gcovr/gcovr/blob/f42ab8f0a1316e16a938545686d707ff624f63ce/gcovr/formats/cobertura/write.py#L73-L75

I'm not sure if this rationale still holds? By looking at JSON output there seems to be a list of functions for each file, including their line numbers.

So probably the Cobertura reporter can be updated to support functions?
If so, then the correct output would be as follows:
```xml
		<methods>
			<method name="func1"  hits="7"  signature="(signature1)" >
				<lines><line number="40"  hits="7" /></lines>
			</method>
			<method name="func2"  hits="0"  signature="(signature2)" >
				<lines><line number="8"  hits="0" /></lines>
			</method>
		</methods>
```

**Comment by Spacetown** [comment]
> Currently Cobertura reporter does not fill the `<methods>` element, leaving it blank. The reasoning for that is as folows:
> 
> https://github.com/gcovr/gcovr/blob/f42ab8f0a1316e16a938545686d707ff624f63ce/gcovr/formats/cobertura/write.py#L73-L75
> 
> I'm not sure if this rationale still holds? By looking at JSON output there seems to be a list of functions for each file, including their line numbers.

It still true since we do not have full information needed for the report.

> So probably the Cobertura reporter can be updated to support functions? If so, then the correct output would be as follows:
> 
> ```xml
> 		<methods>
> 			<method name="func1"  hits="7"  signature="(signature1)" >
> 				<lines><line number="40"  hits="7" /></lines>
> 			</method>
> 			<method name="func2"  hits="0"  signature="(signature2)" >
> 				<lines><line number="8"  hits="0" /></lines>
> 			</method>
> 		</methods>
> ```

This example is invalid according to the DTD:
https://github.com/gcovr/gcovr/blob/f42ab8f0a1316e16a938545686d707ff624f63ce/gcovr/tests/cobertura.coverage-04.dtd#L41-L46

The `hits`is not valid here but a `line-rate`, `branch-rate`and `complexity` is required. This information is completely missing, we only have a `block-rate`.

Related #654 .

**Comment by RoadTrain** [comment]
For the record, my example was from the cobertura report generated by [istanbuljs](https://github.com/istanbuljs/istanbuljs). It is indeed not compliant with the spec, but it's working with report parsers and visualizers that we have tried (namely, [ReportGenerator](https://github.com/danielpalme/ReportGenerator)).

Of course I would like for gcovr to be compliant with the spec, and I'm looking forward for this kind of support.
Thanks!

**Comment by Spacetown** [comment]
There is already an issue since Apr 2021 related to the wrong report format, see https://github.com/istanbuljs/istanbuljs/issues/603.

[ReportGenerator](https://github.com/danielpalme/ReportGenerator) doesn't validate input against the DTD. It only uses the expected arguments and ignores additional ones. The reports generated by the tool are DTD conform.

**Comment by RoadTrain** [comment]
Well, apparently there's an alternative spec, which is less strict: https://github.com/cobertura/cobertura/blob/master/cobertura/src/site/htdocs/xml/coverage-loose.dtd
Anyway, I think it's better to conform to the stricter spec.
