### ISSUE TITLE
Replace md5 with sha256 or other hash supported by FIPS enabled OS

### ISSUE THREAD

**Issue by austride** [gcovr/gcovr#848]
**Describe the bug**
gcovr fails to generate html when using "--html-details" option when running on FIPS enabled Operating Systems (e.g. RHEL 8).

**To Reproduce**
1. run gcovr using the --html-details option

**Expected behavior**
Generate HTML report without error.

**Screenshots**
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/usr/local/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/gcovr/__main__.py", line 333, in main
    error_occurred = print_reports(covdata, options)
  File "/usr/local/lib/python3.9/site-packages/gcovr/__main__.py", line 518, in print_reports
    if generator(covdata, output.abspath, options):
  File "/usr/local/lib/python3.9/site-packages/gcovr/writer/html/__init__.py", line 420, in print_html_report
    cdata_sourcefile[f] = _make_short_sourcename(
  File "/usr/local/lib/python3.9/site-packages/gcovr/writer/html/__init__.py", line 847, in _make_short_sourcename
    hashlib.md5(filename.encode("utf-8")).hexdigest(),
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for fips

**Desktop (please complete the following information):**
 - OS: RHEL8
 - GCOVR version 6

**Additional context**
For a temporary workaround:
Replace md5 with sha256 in the following two files
/usr/local/lib/python*/site-packages/gcovr/writer/html/__init__.py
/usr/local/lib/python*/site-packages/gcovr/writer/coveralls.py

**Comment by latk** [comment]
Gvovr does not use this hash function in any security-relevant way. We could have used a noncryptographic hash function like FNV (or Python's built-in hash feature) for the same effect. Thus, it is regrettable that FIPS seems to prevent this benign use.

But it's good to know that Python doesn't seem to guarantee which hash functions are available. How complicated would it be to select MD5 by default but fall back to a different function at runtime?

I don't want to create a configuration option for this (the hash is just an implementation detail to safely truncate filenames). And I don't want to switch away from MD5 because we'd otherwise see a lot of churn in the test suite.

**Comment by Spacetown** [comment]
I can check on this. There is a set [hashlib.algorithms_available](https://docs.python.org/3/library/hashlib.html#hashlib.algorithms_available) where we can check for md5 and other hashes.

**Comment by Spacetown** [comment]
@latk If md5 isn't available we can't generate coveralls and lcov reports anymore since the require md5. The only possible thing we could do is to use sha256 for the HTML file names if md5 isn't available.

In [algorithms_guaranteed](https://docs.python.org/3/library/hashlib.html#hashlib.algorithms_guaranteed) it's mentioned following:
```
Note that ‘md5’ is in this list despite some upstream vendors offering an odd “FIPS compliant” Python build that excludes it.
```

**Comment by guyhardcastle** [comment]
@Spacetown In python >= 3.9, there is a "userforsecurity" flag that can be passed to [hashlib.md5()](https://docs.python.org/3/library/hashlib.html#hashlib.new). Setting this to False will allow it to be used on FIPS enabled systems.

**Comment by Spacetown** [comment]
@guyhardcastle Thanks for this hint. This would be a solution for newer python versions we can add.
