### ISSUE TITLE
Read configuration from `pyproject.toml`

### ISSUE THREAD

**Issue by LecrisUT** [gcovr/gcovr#875]
In project that already have a `pyproject.toml`, e.g. for providing `pre-commit`, `docs` dependencies; it would be useful to merge the `gcovr` configuration to that file as well.

**Comment by Spacetown** [comment]
The `pyproject.yml` is used for python projects but `gcovr` analysis C/C++ projects. @latk What's your opinion on this?

**Comment by latk** [comment]
I'm weakly opposed, but mostly because I think it can't be done in the near future.

* gcovr is aimed at projects using GCC/Clang for which there is no common config file format. Gcovr does have additional uses (it isn't actually specific to C/C++), but it might not be worth spending too much effort on such use cases. As a Python developer I am :angry: at tools that don't support pyproject.toml (like flake8…), but as a gcovr maintainer I really don't see the point.

* The gcovr config format seems to be in perpetual beta, so doing changes here would be possible. However, its current design is incompatible with TOML. Key feature of the gcovr config format is that you can take most CLI options like `--exclude foo --exclude bar` and turn them into a config file

  ```ini
  exclude = foo
  exclude = bar
  ```

  This neat trick allows us to reuse CLI argument parsing for config file parsing, which is useful for repeated args and more complex types like filters. But this works in terms of "actions" that are executed in order and might store or append data somewhere. It is not directly a format for explicitly creating a certain data structure.

   In contrast, TOML describes a JSON-ish data structure that we would then have to parse. TOML does not allow repeated keys.

I am very in favour of re-designing the configuration system, likely using TOML. Once that's done, it may be sensible to also support loading the config from a pyproject.toml. But the difficult part is coming up with a good design first.

An example of something that might be possible with TOML that's not possible with the current flat CLI-style configuration: Defining multiple reports of the same "type". For example:

```toml
[[report]]
writer = "html-details"
output = "coverage/blue.html"
html.theme = "blue"

[[report]]
writer = "html-details"
output = "coverage/green.html"
html.theme = "green"
```

**Comment by LecrisUT** [comment]
This request is mostly because project maintainers want to keep the front-page of the git page as compact as possible, and seeing how extended some other projects can get, I tend to agree with that sentiment. Stuff like `codecov.yaml` support having them in `.github` folder for that, and that makes sense because it is only used when hosted, but this one is a bit trickier because the user would want to use it as well.

> Key feature of the gcovr config format is that you can take most CLI options like `--exclude foo --exclude bar` and turn them into a config file

Couldn't these be turned into arrays?

**Comment by Spacetown** [comment]
@LecrisUT  Can you do a review of the linked PR? You can also install it from my fork to test it in your environment.
