### ISSUE TITLE
Gcovr does not create necessary directories when output is html details

### ISSUE THREAD

**Issue by Phyks** [gcovr/gcovr#90]
Hi,

Gcovr is not creating the necessary directories when the output is set to `--html-details` on my machine (Windows, Python34). Then, it fails with a traceback indicating that the current target file is not writable. If I manually create the necessary directories, it exports all the stuff fine.

Here is my current command line:

```
> python D:\gcovr\scripts\gcovr --gcov-executable=PATH_TO_gcov.exe -r . --html --html-details -o reports/gcovr/index.html
```

Moreover, although it created all the necessary files, the URLs are not correct. I have source files in a `src` dir and header files in a `header` dir, and all the build files (gcno + gcda) in a `build` dir. When running the above command in the common parent dir, I get a `index.src` and a `index.header` directories under the html output path, but the URLs link to the html files without the `index.[src|header]` prefix and then they do not work.

Thanks

**Comment by latk** [comment]
It is the expected behaviour that gcovr doesn't create the output directories. This behaviour is in line with other command line programs.

The HTML-details were a bit broken under Windows and Python 3, but that should be fixed by now. Can you try upgrading to the development version of gcovr?

I am closing this issue for now. If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.
