### ISSUE TITLE
Multiple root directories

### ISSUE THREAD

**Issue by Phyks** [gcovr/gcovr#91]
Hi,

I have the following structure in my root folder: a `src` folder containing the source files, a `header` folder containing the header files and a `build` folder containing all the gcno and gcda files.

Beside this, I also have other folders, which I do not want to include in the gcovr report. For instance, an `include` dir containing external libs I do not want to track using gcovr.

Currently, I have multiple excludes args to exclude these folder. But it would be really nice to be able to only add the relevant folders (instead of excluding folders). Maybe this is already possible, but I could not find any documentation on this point.

Thanks

**Comment by sleary78** [comment]
agreed this would be nice.

**Comment by varzan** [comment]
I also think this would be an awesome feature!

**Comment by latk** [comment]
The root directory isn't just the start point from which the search for coverage data starts, but also the path relative to which directory names are mangled. Because of that, the concept of multiple root dirs seems non-sensical to me.

Perhaps using `--filter` instead of `--exclude` might be helpful. It is also possible to run gcov externally and then pass gcovr only those files you are interested in, with the `--use-gcov-files` option.
