### ISSUE TITLE
Coverage data got filtered out for no reason

### ISSUE THREAD

**Issue by mrx23dot** [gcovr/gcovr#99]
My coverage data got filtered out for no reason. (I didn't give any filtering)

Running gcov: 'gcov C:\KBData\Sandbox\Project\Out\ut_utils.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory C:\KBData\Sandbox\Project\Out' in 'C:\KBData\Sandbox\Project\Out'
Filtering gcov file C~#KBData#Sandbox#Project#Test#ut_utils.c.gcov

I guessed the reqexp worked somehow differently.

Same setup worked on one PC, but not on the other. I had to comment out the filtering code, to solve it.
Using GCOVR 3.2, Windows 7 x64, MinGW 4.8

Commenting out the following solved it:
-#    for i in range(0,len(options.filter)):
-#        if options.filter[i].match(fname):
-#            filtered_fname = options.root_filter.sub('',fname)
-#            break
-# CAUSED PROBLEMS!!!
-#    if filtered_fname is None:
-#        if options.verbose:
-#            sys.stdout.write("  Filtering coverage data for file %s\n" % fname)
-#        return

**Comment by bmutev** [comment]
I can second that, today I have stumbled on this issue too. Without specifying any filter the generated coverage data gets filtered out. If, for test purpose, '-f="*"' is added to the command line, the data is printed out.

**Comment by latk** [comment]
Filters on Windows received an important fix with PR #158. This may have also fixed your problems.

Note there is a filter even when you don't give a `-f`/`--filter` argument:

 - the `-r`/`--root` gcovr argument, or if that is missing
 - the current working directory.

The goal is that coverage is only calculated for your project, not for system headers.

Please test the current development version of gcovr by installing directly from GitHub:

    pip install git+https://github.com/gcovr/gcovr.git

If the problems persist, please add more details so that this issue can be reopened.

Please also contribute your experience to the discussion on issue #191 about Windows filters.
